<?php

use Illuminate\Database\Seeder;

class HrmQuanhuyenTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon\Carbon::now();
        DB::table('hrm_quanhuyen')->insert(
            [
                [ 'id' => '1', 'ma_quanhuyen' => '51001', 'ten_quanhuyen' => 'Huyện Bình Chánh', 'created_at' => $now],
                [ 'id' => '2', 'ma_quanhuyen' => '51002', 'ten_quanhuyen' => 'Huyện Cần Giờ', 'created_at' => $now],
                [ 'id' => '3', 'ma_quanhuyen' => '51003', 'ten_quanhuyen' => 'Huyện Củ Chi', 'created_at' => $now],
                [ 'id' => '4', 'ma_quanhuyen' => '51004', 'ten_quanhuyen' => 'Huyện Hóc Môn', 'created_at' => $now],
                [ 'id' => '5', 'ma_quanhuyen' => '51005', 'ten_quanhuyen' => 'Huyện Nhà Bè', 'created_at' => $now],
                [ 'id' => '6', 'ma_quanhuyen' => '51006', 'ten_quanhuyen' => 'Quận 1', 'created_at' => $now],
                [ 'id' => '7', 'ma_quanhuyen' => '51007', 'ten_quanhuyen' => 'Quận 10', 'created_at' => $now],
                [ 'id' => '8', 'ma_quanhuyen' => '51008', 'ten_quanhuyen' => 'Quận 11', 'created_at' => $now],
                [ 'id' => '9', 'ma_quanhuyen' => '51009', 'ten_quanhuyen' => 'Quận 12', 'created_at' => $now],
                [ 'id' => '10', 'ma_quanhuyen' => '51010', 'ten_quanhuyen' => 'Quận 2', 'created_at' => $now],
                [ 'id' => '11', 'ma_quanhuyen' => '51011', 'ten_quanhuyen' => 'Quận 3', 'created_at' => $now],
                [ 'id' => '12', 'ma_quanhuyen' => '51012', 'ten_quanhuyen' => 'Quận 4', 'created_at' => $now],
                [ 'id' => '13', 'ma_quanhuyen' => '51013', 'ten_quanhuyen' => 'Quận 5', 'created_at' => $now],
                [ 'id' => '14', 'ma_quanhuyen' => '51014', 'ten_quanhuyen' => 'Quận 6', 'created_at' => $now],
                [ 'id' => '15', 'ma_quanhuyen' => '51015', 'ten_quanhuyen' => 'Quận 7', 'created_at' => $now],
                [ 'id' => '16', 'ma_quanhuyen' => '51016', 'ten_quanhuyen' => 'Quận 8', 'created_at' => $now],
                [ 'id' => '17', 'ma_quanhuyen' => '51017', 'ten_quanhuyen' => 'Quận 9', 'created_at' => $now],
                [ 'id' => '18', 'ma_quanhuyen' => '51018', 'ten_quanhuyen' => 'Quận Bình Tân', 'created_at' => $now],
                [ 'id' => '19', 'ma_quanhuyen' => '51019', 'ten_quanhuyen' => 'Quận Bình Thạnh', 'created_at' => $now],
                [ 'id' => '20', 'ma_quanhuyen' => '51020', 'ten_quanhuyen' => 'Quận Gò Vấp', 'created_at' => $now],
                [ 'id' => '21', 'ma_quanhuyen' => '51021', 'ten_quanhuyen' => 'Quận Phú Nhuận', 'created_at' => $now],
                [ 'id' => '22', 'ma_quanhuyen' => '51022', 'ten_quanhuyen' => 'Quận Tân Bình', 'created_at' => $now],
                [ 'id' => '23', 'ma_quanhuyen' => '51023', 'ten_quanhuyen' => 'Quận Tân Phú', 'created_at' => $now],
                [ 'id' => '24', 'ma_quanhuyen' => '51024', 'ten_quanhuyen' => 'Quận Thủ Đức', 'created_at' => $now],
                [ 'id' => '25', 'ma_quanhuyen' => '52001', 'ten_quanhuyen' => 'Huyện Bến Lức', 'created_at' => $now],
                [ 'id' => '26', 'ma_quanhuyen' => '52002', 'ten_quanhuyen' => 'Huyện Cần Đước', 'created_at' => $now],
                [ 'id' => '27', 'ma_quanhuyen' => '52003', 'ten_quanhuyen' => 'Huyện Cần Giuộc', 'created_at' => $now],
                [ 'id' => '28', 'ma_quanhuyen' => '52004', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '29', 'ma_quanhuyen' => '52005', 'ten_quanhuyen' => 'Huyện Đức Hòa', 'created_at' => $now],
                [ 'id' => '30', 'ma_quanhuyen' => '52006', 'ten_quanhuyen' => 'Huyện Đức Huệ', 'created_at' => $now],
                [ 'id' => '31', 'ma_quanhuyen' => '52007', 'ten_quanhuyen' => 'Huyện Mộc Hóa', 'created_at' => $now],
                [ 'id' => '32', 'ma_quanhuyen' => '52008', 'ten_quanhuyen' => 'Huyện Tân Hưng', 'created_at' => $now],
                [ 'id' => '33', 'ma_quanhuyen' => '52009', 'ten_quanhuyen' => 'Huyện Tân Thạnh', 'created_at' => $now],
                [ 'id' => '34', 'ma_quanhuyen' => '52010', 'ten_quanhuyen' => 'Huyện Tân Trụ', 'created_at' => $now],
                [ 'id' => '35', 'ma_quanhuyen' => '52011', 'ten_quanhuyen' => 'Huyện Thạnh Hóa', 'created_at' => $now],
                [ 'id' => '36', 'ma_quanhuyen' => '52012', 'ten_quanhuyen' => 'Huyện Thủ Thừa', 'created_at' => $now],
                [ 'id' => '37', 'ma_quanhuyen' => '52013', 'ten_quanhuyen' => 'Huyện Vĩnh Hưng', 'created_at' => $now],
                [ 'id' => '38', 'ma_quanhuyen' => '52014', 'ten_quanhuyen' => 'Thành phố Tân An', 'created_at' => $now],
                [ 'id' => '39', 'ma_quanhuyen' => '53001', 'ten_quanhuyen' => 'Huyện Cái Bè', 'created_at' => $now],
                [ 'id' => '40', 'ma_quanhuyen' => '53002', 'ten_quanhuyen' => 'Huyện Cai Lậy', 'created_at' => $now],
                [ 'id' => '41', 'ma_quanhuyen' => '53003', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '42', 'ma_quanhuyen' => '53004', 'ten_quanhuyen' => 'Huyện Chợ Gạo', 'created_at' => $now],
                [ 'id' => '43', 'ma_quanhuyen' => '53005', 'ten_quanhuyen' => 'Huyện Gò Công Đông', 'created_at' => $now],
                [ 'id' => '44', 'ma_quanhuyen' => '53006', 'ten_quanhuyen' => 'Huyện Gò Công Tây', 'created_at' => $now],
                [ 'id' => '45', 'ma_quanhuyen' => '53007', 'ten_quanhuyen' => 'Huyện Tân Phú Đông', 'created_at' => $now],
                [ 'id' => '46', 'ma_quanhuyen' => '53008', 'ten_quanhuyen' => 'Huyện Tân Phước', 'created_at' => $now],
                [ 'id' => '47', 'ma_quanhuyen' => '53009', 'ten_quanhuyen' => 'Thành phố Mỹ Tho', 'created_at' => $now],
                [ 'id' => '48', 'ma_quanhuyen' => '53010', 'ten_quanhuyen' => 'Thị xã Gò Công', 'created_at' => $now],
                [ 'id' => '49', 'ma_quanhuyen' => '54001', 'ten_quanhuyen' => 'Huyện Ba Tri', 'created_at' => $now],
                [ 'id' => '50', 'ma_quanhuyen' => '54002', 'ten_quanhuyen' => 'Huyện Bình Đại', 'created_at' => $now],
                [ 'id' => '51', 'ma_quanhuyen' => '54003', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '52', 'ma_quanhuyen' => '54004', 'ten_quanhuyen' => 'Huyện Chợ Lách', 'created_at' => $now],
                [ 'id' => '53', 'ma_quanhuyen' => '54005', 'ten_quanhuyen' => 'Huyện Giồng Trôm', 'created_at' => $now],
                [ 'id' => '54', 'ma_quanhuyen' => '54006', 'ten_quanhuyen' => 'Huyện Mỏ Cày Bắc', 'created_at' => $now],
                [ 'id' => '55', 'ma_quanhuyen' => '54007', 'ten_quanhuyen' => 'Huyện Mỏ Cày Nam', 'created_at' => $now],
                [ 'id' => '56', 'ma_quanhuyen' => '54008', 'ten_quanhuyen' => 'Huyện Thạnh Phú', 'created_at' => $now],
                [ 'id' => '57', 'ma_quanhuyen' => '54009', 'ten_quanhuyen' => 'Thành phố Bến Tre', 'created_at' => $now],
                [ 'id' => '58', 'ma_quanhuyen' => '55101', 'ten_quanhuyen' => 'Huyện Càng Long', 'created_at' => $now],
                [ 'id' => '59', 'ma_quanhuyen' => '55102', 'ten_quanhuyen' => 'Huyện Cầu Kè', 'created_at' => $now],
                [ 'id' => '60', 'ma_quanhuyen' => '55103', 'ten_quanhuyen' => 'Huyện Cầu Ngang', 'created_at' => $now],
                [ 'id' => '61', 'ma_quanhuyen' => '55104', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '62', 'ma_quanhuyen' => '55105', 'ten_quanhuyen' => 'Huyện Duyên Hải', 'created_at' => $now],
                [ 'id' => '63', 'ma_quanhuyen' => '55106', 'ten_quanhuyen' => 'Huyện Tiểu Cần', 'created_at' => $now],
                [ 'id' => '64', 'ma_quanhuyen' => '55107', 'ten_quanhuyen' => 'Huyện Trà Cú', 'created_at' => $now],
                [ 'id' => '65', 'ma_quanhuyen' => '55108', 'ten_quanhuyen' => 'Thành phố Trà Vinh', 'created_at' => $now],
                [ 'id' => '66', 'ma_quanhuyen' => '56001', 'ten_quanhuyen' => 'Thị xã Bình Minh', 'created_at' => $now],
                [ 'id' => '67', 'ma_quanhuyen' => '56002', 'ten_quanhuyen' => 'Huyện Long Hồ', 'created_at' => $now],
                [ 'id' => '68', 'ma_quanhuyen' => '56003', 'ten_quanhuyen' => 'Huyện Mang Thít', 'created_at' => $now],
                [ 'id' => '69', 'ma_quanhuyen' => '56004', 'ten_quanhuyen' => 'Huyện Tam Bình', 'created_at' => $now],
                [ 'id' => '70', 'ma_quanhuyen' => '56005', 'ten_quanhuyen' => 'Huyện Trà Ôn', 'created_at' => $now],
                [ 'id' => '71', 'ma_quanhuyen' => '56006', 'ten_quanhuyen' => 'Huyện Vũng Liêm', 'created_at' => $now],
                [ 'id' => '72', 'ma_quanhuyen' => '56007', 'ten_quanhuyen' => 'Thành phố Vĩnh Long', 'created_at' => $now],
                [ 'id' => '73', 'ma_quanhuyen' => '57001', 'ten_quanhuyen' => 'Huyện Cao Lãnh', 'created_at' => $now],
                [ 'id' => '74', 'ma_quanhuyen' => '57002', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '75', 'ma_quanhuyen' => '57003', 'ten_quanhuyen' => 'Huyện Hồng Ngự', 'created_at' => $now],
                [ 'id' => '76', 'ma_quanhuyen' => '57004', 'ten_quanhuyen' => 'Huyện Lai Vung', 'created_at' => $now],
                [ 'id' => '77', 'ma_quanhuyen' => '57005', 'ten_quanhuyen' => 'Huyện Lấp Vò', 'created_at' => $now],
                [ 'id' => '78', 'ma_quanhuyen' => '57006', 'ten_quanhuyen' => 'Huyện Tam Nông', 'created_at' => $now],
                [ 'id' => '79', 'ma_quanhuyen' => '57007', 'ten_quanhuyen' => 'Huyện Tân Hồng', 'created_at' => $now],
                [ 'id' => '80', 'ma_quanhuyen' => '57008', 'ten_quanhuyen' => 'Huyện Thanh Bình', 'created_at' => $now],
                [ 'id' => '81', 'ma_quanhuyen' => '57009', 'ten_quanhuyen' => 'Huyện Tháp Mười', 'created_at' => $now],
                [ 'id' => '82', 'ma_quanhuyen' => '57010', 'ten_quanhuyen' => 'Thành phố Cao Lãnh', 'created_at' => $now],
                [ 'id' => '83', 'ma_quanhuyen' => '57011', 'ten_quanhuyen' => 'Thị xã Hồng Ngự', 'created_at' => $now],
                [ 'id' => '84', 'ma_quanhuyen' => '57012', 'ten_quanhuyen' => 'Thị xã Sa Đéc', 'created_at' => $now],
                [ 'id' => '85', 'ma_quanhuyen' => '58001', 'ten_quanhuyen' => 'Huyện An Phú', 'created_at' => $now],
                [ 'id' => '86', 'ma_quanhuyen' => '58002', 'ten_quanhuyen' => 'Huyện Châu Phú', 'created_at' => $now],
                [ 'id' => '87', 'ma_quanhuyen' => '58003', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '88', 'ma_quanhuyen' => '58004', 'ten_quanhuyen' => 'Huyện Chợ Mới', 'created_at' => $now],
                [ 'id' => '89', 'ma_quanhuyen' => '58005', 'ten_quanhuyen' => 'Huyện Phú Tân', 'created_at' => $now],
                [ 'id' => '90', 'ma_quanhuyen' => '58006', 'ten_quanhuyen' => 'Huyện Tịnh Biên', 'created_at' => $now],
                [ 'id' => '91', 'ma_quanhuyen' => '58007', 'ten_quanhuyen' => 'Huyện Thoại Sơn', 'created_at' => $now],
                [ 'id' => '92', 'ma_quanhuyen' => '58008', 'ten_quanhuyen' => 'Huyện Tri Tôn', 'created_at' => $now],
                [ 'id' => '93', 'ma_quanhuyen' => '58009', 'ten_quanhuyen' => 'Thành phố Long Xuyên', 'created_at' => $now],
                [ 'id' => '94', 'ma_quanhuyen' => '58010', 'ten_quanhuyen' => 'Thị xã Châu Đốc', 'created_at' => $now],
                [ 'id' => '95', 'ma_quanhuyen' => '58011', 'ten_quanhuyen' => 'Thị xã Tân Châu', 'created_at' => $now],
                [ 'id' => '96', 'ma_quanhuyen' => '59001', 'ten_quanhuyen' => 'Huyện An Biên', 'created_at' => $now],
                [ 'id' => '97', 'ma_quanhuyen' => '59002', 'ten_quanhuyen' => 'Huyện An Minh', 'created_at' => $now],
                [ 'id' => '98', 'ma_quanhuyen' => '59003', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '99', 'ma_quanhuyen' => '59004', 'ten_quanhuyen' => 'Huyện Gò Quao', 'created_at' => $now],
                [ 'id' => '100', 'ma_quanhuyen' => '59005', 'ten_quanhuyen' => 'Huyện Giang Thành', 'created_at' => $now],
                [ 'id' => '101', 'ma_quanhuyen' => '59006', 'ten_quanhuyen' => 'Huyện Giồng Giềng', 'created_at' => $now],
                [ 'id' => '102', 'ma_quanhuyen' => '59007', 'ten_quanhuyen' => 'Huyện Hòn Đất', 'created_at' => $now],
                [ 'id' => '103', 'ma_quanhuyen' => '59008', 'ten_quanhuyen' => 'Huyện Kiên Hải', 'created_at' => $now],
                [ 'id' => '104', 'ma_quanhuyen' => '59009', 'ten_quanhuyen' => 'Huyện Kiên Lương', 'created_at' => $now],
                [ 'id' => '105', 'ma_quanhuyen' => '59010', 'ten_quanhuyen' => 'Huyện Phú Quốc', 'created_at' => $now],
                [ 'id' => '106', 'ma_quanhuyen' => '59011', 'ten_quanhuyen' => 'Huyện Tân Hiệp', 'created_at' => $now],
                [ 'id' => '107', 'ma_quanhuyen' => '59012', 'ten_quanhuyen' => 'Huyện U Minh Thượng', 'created_at' => $now],
                [ 'id' => '108', 'ma_quanhuyen' => '59013', 'ten_quanhuyen' => 'Huyện Vĩnh Thuận', 'created_at' => $now],
                [ 'id' => '109', 'ma_quanhuyen' => '59014', 'ten_quanhuyen' => 'Thành phố Rạch Giá', 'created_at' => $now],
                [ 'id' => '110', 'ma_quanhuyen' => '59015', 'ten_quanhuyen' => 'Thị xã Hà Tiên', 'created_at' => $now],
                [ 'id' => '111', 'ma_quanhuyen' => '60001', 'ten_quanhuyen' => 'Huyện Cờ Đỏ', 'created_at' => $now],
                [ 'id' => '112', 'ma_quanhuyen' => '60002', 'ten_quanhuyen' => 'Huyện Phong Điền', 'created_at' => $now],
                [ 'id' => '113', 'ma_quanhuyen' => '60003', 'ten_quanhuyen' => 'Huyện Thới Lai', 'created_at' => $now],
                [ 'id' => '114', 'ma_quanhuyen' => '60004', 'ten_quanhuyen' => 'Huyện Vĩnh Thạnh', 'created_at' => $now],
                [ 'id' => '115', 'ma_quanhuyen' => '60005', 'ten_quanhuyen' => 'Quận Bình Thuỷ', 'created_at' => $now],
                [ 'id' => '116', 'ma_quanhuyen' => '60006', 'ten_quanhuyen' => 'Quận Cái Răng', 'created_at' => $now],
                [ 'id' => '117', 'ma_quanhuyen' => '60007', 'ten_quanhuyen' => 'Quận Ninh Kiều', 'created_at' => $now],
                [ 'id' => '118', 'ma_quanhuyen' => '60008', 'ten_quanhuyen' => 'Quận Ô Môn', 'created_at' => $now],
                [ 'id' => '119', 'ma_quanhuyen' => '60009', 'ten_quanhuyen' => 'Quận Thốt Nốt', 'created_at' => $now],
                [ 'id' => '120', 'ma_quanhuyen' => '61001', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '121', 'ma_quanhuyen' => '61002', 'ten_quanhuyen' => 'Huyện Châu Thành A', 'created_at' => $now],
                [ 'id' => '122', 'ma_quanhuyen' => '61003', 'ten_quanhuyen' => 'Huyện Phụng Hiệp', 'created_at' => $now],
                [ 'id' => '123', 'ma_quanhuyen' => '61004', 'ten_quanhuyen' => 'Huyện Vị Thuỷ', 'created_at' => $now],
                [ 'id' => '124', 'ma_quanhuyen' => '61005', 'ten_quanhuyen' => 'Huyện Long Mỹ', 'created_at' => $now],
                [ 'id' => '125', 'ma_quanhuyen' => '61006', 'ten_quanhuyen' => 'Thành phố Vị Thanh', 'created_at' => $now],
                [ 'id' => '126', 'ma_quanhuyen' => '61007', 'ten_quanhuyen' => 'Thị xã Ngã Bảy', 'created_at' => $now],
                [ 'id' => '127', 'ma_quanhuyen' => '62001', 'ten_quanhuyen' => 'Huyện Cù Lao Dung', 'created_at' => $now],
                [ 'id' => '128', 'ma_quanhuyen' => '62002', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '129', 'ma_quanhuyen' => '62003', 'ten_quanhuyen' => 'Huyện Kế Sách', 'created_at' => $now],
                [ 'id' => '130', 'ma_quanhuyen' => '62004', 'ten_quanhuyen' => 'Huyện Long Phú', 'created_at' => $now],
                [ 'id' => '131', 'ma_quanhuyen' => '62005', 'ten_quanhuyen' => 'Huyện Mỹ Tú', 'created_at' => $now],
                [ 'id' => '132', 'ma_quanhuyen' => '62006', 'ten_quanhuyen' => 'Huyện Mỹ Xuyên', 'created_at' => $now],
                [ 'id' => '133', 'ma_quanhuyen' => '62007', 'ten_quanhuyen' => 'Thị xã Ngã Năm', 'created_at' => $now],
                [ 'id' => '134', 'ma_quanhuyen' => '62008', 'ten_quanhuyen' => 'Huyện Thạnh Trị', 'created_at' => $now],
                [ 'id' => '135', 'ma_quanhuyen' => '62009', 'ten_quanhuyen' => 'Huyện Trần Đề', 'created_at' => $now],
                [ 'id' => '136', 'ma_quanhuyen' => '62010', 'ten_quanhuyen' => 'Thị xã  Vĩnh Châu', 'created_at' => $now],
                [ 'id' => '137', 'ma_quanhuyen' => '62011', 'ten_quanhuyen' => 'Thành phố Sóc Trăng', 'created_at' => $now],
                [ 'id' => '138', 'ma_quanhuyen' => '63001', 'ten_quanhuyen' => 'Huyện Đông Hải', 'created_at' => $now],
                [ 'id' => '139', 'ma_quanhuyen' => '63002', 'ten_quanhuyen' => 'Huyện Giá Rai', 'created_at' => $now],
                [ 'id' => '140', 'ma_quanhuyen' => '63003', 'ten_quanhuyen' => 'Huyện Hòa Bình', 'created_at' => $now],
                [ 'id' => '141', 'ma_quanhuyen' => '63004', 'ten_quanhuyen' => 'Huyện Hồng Dân', 'created_at' => $now],
                [ 'id' => '142', 'ma_quanhuyen' => '63005', 'ten_quanhuyen' => 'Huyện Phước Long', 'created_at' => $now],
                [ 'id' => '143', 'ma_quanhuyen' => '63006', 'ten_quanhuyen' => 'Huyện Vĩnh Lợi', 'created_at' => $now],
                [ 'id' => '144', 'ma_quanhuyen' => '63007', 'ten_quanhuyen' => 'Thành phố Bạc Liêu', 'created_at' => $now],
                [ 'id' => '145', 'ma_quanhuyen' => '64001', 'ten_quanhuyen' => 'Huyện Cái Nước', 'created_at' => $now],
                [ 'id' => '146', 'ma_quanhuyen' => '64002', 'ten_quanhuyen' => 'Huyện Đầm Dơi', 'created_at' => $now],
                [ 'id' => '147', 'ma_quanhuyen' => '64003', 'ten_quanhuyen' => 'Huyện Năm Căn', 'created_at' => $now],
                [ 'id' => '148', 'ma_quanhuyen' => '64004', 'ten_quanhuyen' => 'Huyện Ngọc Hiển', 'created_at' => $now],
                [ 'id' => '149', 'ma_quanhuyen' => '64005', 'ten_quanhuyen' => 'Huyện Phú Tân', 'created_at' => $now],
                [ 'id' => '150', 'ma_quanhuyen' => '64006', 'ten_quanhuyen' => 'Huyện Thới Bình', 'created_at' => $now],
                [ 'id' => '151', 'ma_quanhuyen' => '64007', 'ten_quanhuyen' => 'Huyện Trần Văn Thời', 'created_at' => $now],
                [ 'id' => '152', 'ma_quanhuyen' => '64008', 'ten_quanhuyen' => 'Huyện U Minh', 'created_at' => $now],
                [ 'id' => '153', 'ma_quanhuyen' => '64009', 'ten_quanhuyen' => 'Thành phố Cà Mau', 'created_at' => $now],
                [ 'id' => '154', 'ma_quanhuyen' => '41001', 'ten_quanhuyen' => 'Huyện Đắk Glei', 'created_at' => $now],
                [ 'id' => '155', 'ma_quanhuyen' => '41002', 'ten_quanhuyen' => 'Huyện Đắk Hà', 'created_at' => $now],
                [ 'id' => '156', 'ma_quanhuyen' => '41003', 'ten_quanhuyen' => 'Huyện Đắk Tô', 'created_at' => $now],
                [ 'id' => '157', 'ma_quanhuyen' => '41004', 'ten_quanhuyen' => 'Huyện Kon Plông', 'created_at' => $now],
                [ 'id' => '158', 'ma_quanhuyen' => '41005', 'ten_quanhuyen' => 'Huyện Kon Rẫy', 'created_at' => $now],
                [ 'id' => '159', 'ma_quanhuyen' => '41006', 'ten_quanhuyen' => 'Huyện Ngọc Hồi', 'created_at' => $now],
                [ 'id' => '160', 'ma_quanhuyen' => '41007', 'ten_quanhuyen' => 'Huyện Sa Thầy', 'created_at' => $now],
                [ 'id' => '161', 'ma_quanhuyen' => '41008', 'ten_quanhuyen' => 'Huyện Tu Mơ Rông', 'created_at' => $now],
                [ 'id' => '162', 'ma_quanhuyen' => '41009', 'ten_quanhuyen' => 'Thành phố Kon Tum', 'created_at' => $now],
                [ 'id' => '163', 'ma_quanhuyen' => '42001', 'ten_quanhuyen' => 'Huyện Chư Păh', 'created_at' => $now],
                [ 'id' => '164', 'ma_quanhuyen' => '42002', 'ten_quanhuyen' => 'Huyện Chư Prông', 'created_at' => $now],
                [ 'id' => '165', 'ma_quanhuyen' => '42003', 'ten_quanhuyen' => 'Huyện Chư Pưh', 'created_at' => $now],
                [ 'id' => '166', 'ma_quanhuyen' => '42004', 'ten_quanhuyen' => 'Huyện Chư Sê', 'created_at' => $now],
                [ 'id' => '167', 'ma_quanhuyen' => '42005', 'ten_quanhuyen' => 'Huyện Đăk Đoa', 'created_at' => $now],
                [ 'id' => '168', 'ma_quanhuyen' => '42006', 'ten_quanhuyen' => 'Huyện Đăk Pơ', 'created_at' => $now],
                [ 'id' => '169', 'ma_quanhuyen' => '42007', 'ten_quanhuyen' => 'Huyện Đức Cơ', 'created_at' => $now],
                [ 'id' => '170', 'ma_quanhuyen' => '42008', 'ten_quanhuyen' => 'Huyện Ia Grai', 'created_at' => $now],
                [ 'id' => '171', 'ma_quanhuyen' => '42009', 'ten_quanhuyen' => 'Huyện Ia Pa', 'created_at' => $now],
                [ 'id' => '172', 'ma_quanhuyen' => '42010', 'ten_quanhuyen' => 'Huyện KBang', 'created_at' => $now],
                [ 'id' => '173', 'ma_quanhuyen' => '42011', 'ten_quanhuyen' => 'Huyện Kông Chro', 'created_at' => $now],
                [ 'id' => '174', 'ma_quanhuyen' => '42012', 'ten_quanhuyen' => 'Huyện Krông Pa', 'created_at' => $now],
                [ 'id' => '175', 'ma_quanhuyen' => '42013', 'ten_quanhuyen' => 'Huyện Mang Yang', 'created_at' => $now],
                [ 'id' => '176', 'ma_quanhuyen' => '42014', 'ten_quanhuyen' => 'Huyện Phú Thiện', 'created_at' => $now],
                [ 'id' => '177', 'ma_quanhuyen' => '42015', 'ten_quanhuyen' => 'Thành phố Pleiku', 'created_at' => $now],
                [ 'id' => '178', 'ma_quanhuyen' => '42016', 'ten_quanhuyen' => 'Thị Xã An Khê', 'created_at' => $now],
                [ 'id' => '179', 'ma_quanhuyen' => '42017', 'ten_quanhuyen' => 'Thị xã Ayun Pa', 'created_at' => $now],
                [ 'id' => '180', 'ma_quanhuyen' => '43001', 'ten_quanhuyen' => 'Huyện Buôn Đôn', 'created_at' => $now],
                [ 'id' => '181', 'ma_quanhuyen' => '43002', 'ten_quanhuyen' => 'Huyện Cư Kuin', 'created_at' => $now],
                [ 'id' => '182', 'ma_quanhuyen' => '43003', 'ten_quanhuyen' => 'Huyện Cư M\'gar', 'created_at' => $now],
                [ 'id' => '183', 'ma_quanhuyen' => '43004', 'ten_quanhuyen' => 'Huyện Ea H\'leo', 'created_at' => $now],
                [ 'id' => '184', 'ma_quanhuyen' => '43005', 'ten_quanhuyen' => 'Huyện Ea Kar', 'created_at' => $now],
                [ 'id' => '185', 'ma_quanhuyen' => '43006', 'ten_quanhuyen' => 'Huyện Ea Súp', 'created_at' => $now],
                [ 'id' => '186', 'ma_quanhuyen' => '43007', 'ten_quanhuyen' => 'Huyện Krông A Na', 'created_at' => $now],
                [ 'id' => '187', 'ma_quanhuyen' => '43008', 'ten_quanhuyen' => 'Huyện Krông Bông', 'created_at' => $now],
                [ 'id' => '188', 'ma_quanhuyen' => '43009', 'ten_quanhuyen' => 'Huyện Krông Búk', 'created_at' => $now],
                [ 'id' => '189', 'ma_quanhuyen' => '43010', 'ten_quanhuyen' => 'Huyện Krông Năng', 'created_at' => $now],
                [ 'id' => '190', 'ma_quanhuyen' => '43011', 'ten_quanhuyen' => 'Huyện Krông Pắc', 'created_at' => $now],
                [ 'id' => '191', 'ma_quanhuyen' => '43012', 'ten_quanhuyen' => 'Huyện Lắk', 'created_at' => $now],
                [ 'id' => '192', 'ma_quanhuyen' => '43013', 'ten_quanhuyen' => 'Huyện M\'Đrắk', 'created_at' => $now],
                [ 'id' => '193', 'ma_quanhuyen' => '43014', 'ten_quanhuyen' => 'Thành phố Buôn Ma Thuột', 'created_at' => $now],
                [ 'id' => '194', 'ma_quanhuyen' => '43015', 'ten_quanhuyen' => 'Thị Xã Buôn Hồ', 'created_at' => $now],
                [ 'id' => '195', 'ma_quanhuyen' => '44001', 'ten_quanhuyen' => 'Huyện Cư Jút', 'created_at' => $now],
                [ 'id' => '196', 'ma_quanhuyen' => '44002', 'ten_quanhuyen' => 'Huyện Đắk Glong', 'created_at' => $now],
                [ 'id' => '197', 'ma_quanhuyen' => '44003', 'ten_quanhuyen' => 'Huyện Đắk Mil', 'created_at' => $now],
                [ 'id' => '198', 'ma_quanhuyen' => '44004', 'ten_quanhuyen' => 'Huyện Đắk R\'Lấp', 'created_at' => $now],
                [ 'id' => '199', 'ma_quanhuyen' => '44005', 'ten_quanhuyen' => 'Huyện Đắk Song', 'created_at' => $now],
                [ 'id' => '200', 'ma_quanhuyen' => '44006', 'ten_quanhuyen' => 'Huyện Krông Nô', 'created_at' => $now],
                [ 'id' => '201', 'ma_quanhuyen' => '44007', 'ten_quanhuyen' => 'Huyện Tuy Đức', 'created_at' => $now],
                [ 'id' => '202', 'ma_quanhuyen' => '44008', 'ten_quanhuyen' => 'Thị xã Gia Nghĩa', 'created_at' => $now],
                [ 'id' => '203', 'ma_quanhuyen' => '45001', 'ten_quanhuyen' => 'Huyện Bảo Lâm', 'created_at' => $now],
                [ 'id' => '204', 'ma_quanhuyen' => '45002', 'ten_quanhuyen' => 'Huyện Cát Tiên', 'created_at' => $now],
                [ 'id' => '205', 'ma_quanhuyen' => '45003', 'ten_quanhuyen' => 'Huyện Di Linh', 'created_at' => $now],
                [ 'id' => '206', 'ma_quanhuyen' => '45004', 'ten_quanhuyen' => 'Huyện Đạ Huoai', 'created_at' => $now],
                [ 'id' => '207', 'ma_quanhuyen' => '45005', 'ten_quanhuyen' => 'Huyện Đạ Tẻh', 'created_at' => $now],
                [ 'id' => '208', 'ma_quanhuyen' => '45006', 'ten_quanhuyen' => 'Huyện Đơn Dương', 'created_at' => $now],
                [ 'id' => '209', 'ma_quanhuyen' => '45007', 'ten_quanhuyen' => 'Huyện Đức Trọng', 'created_at' => $now],
                [ 'id' => '210', 'ma_quanhuyen' => '45008', 'ten_quanhuyen' => 'Huyện Lạc Dương', 'created_at' => $now],
                [ 'id' => '211', 'ma_quanhuyen' => '45009', 'ten_quanhuyen' => 'Huyện Lâm Hà', 'created_at' => $now],
                [ 'id' => '212', 'ma_quanhuyen' => '45010', 'ten_quanhuyen' => 'Thành phố Bảo Lộc', 'created_at' => $now],
                [ 'id' => '213', 'ma_quanhuyen' => '45011', 'ten_quanhuyen' => 'Thành phố Đà Lạt', 'created_at' => $now],
                [ 'id' => '214', 'ma_quanhuyen' => '46101', 'ten_quanhuyen' => 'Huyện Bù Đăng', 'created_at' => $now],
                [ 'id' => '215', 'ma_quanhuyen' => '46102', 'ten_quanhuyen' => 'Huyện Bù Đốp', 'created_at' => $now],
                [ 'id' => '216', 'ma_quanhuyen' => '46103', 'ten_quanhuyen' => 'Huyện Bù Gia Mập', 'created_at' => $now],
                [ 'id' => '217', 'ma_quanhuyen' => '46104', 'ten_quanhuyen' => 'Huyện Chơn Thành', 'created_at' => $now],
                [ 'id' => '218', 'ma_quanhuyen' => '46105', 'ten_quanhuyen' => 'Huyện Đồng Phù', 'created_at' => $now],
                [ 'id' => '219', 'ma_quanhuyen' => '46106', 'ten_quanhuyen' => 'Huyện Hớn Quản', 'created_at' => $now],
                [ 'id' => '220', 'ma_quanhuyen' => '46107', 'ten_quanhuyen' => 'Huyện Lộc Ninh', 'created_at' => $now],
                [ 'id' => '221', 'ma_quanhuyen' => '46108', 'ten_quanhuyen' => 'Thị xã Bình Long', 'created_at' => $now],
                [ 'id' => '222', 'ma_quanhuyen' => '46109', 'ten_quanhuyen' => 'Thị xã Đồng Xoài', 'created_at' => $now],
                [ 'id' => '223', 'ma_quanhuyen' => '46110', 'ten_quanhuyen' => 'Thị xã Phước Long', 'created_at' => $now],
                [ 'id' => '224', 'ma_quanhuyen' => '47001', 'ten_quanhuyen' => 'Huyện Bến Cầu', 'created_at' => $now],
                [ 'id' => '225', 'ma_quanhuyen' => '47002', 'ten_quanhuyen' => 'Huyện Châu Thành', 'created_at' => $now],
                [ 'id' => '226', 'ma_quanhuyen' => '47003', 'ten_quanhuyen' => 'Huyện Dương Minh Châu', 'created_at' => $now],
                [ 'id' => '227', 'ma_quanhuyen' => '47004', 'ten_quanhuyen' => 'Huyện Gò Dầu', 'created_at' => $now],
                [ 'id' => '228', 'ma_quanhuyen' => '47005', 'ten_quanhuyen' => 'Huyện Hòa Thành', 'created_at' => $now],
                [ 'id' => '229', 'ma_quanhuyen' => '47006', 'ten_quanhuyen' => 'Huyện Tân Biên', 'created_at' => $now],
                [ 'id' => '230', 'ma_quanhuyen' => '47007', 'ten_quanhuyen' => 'Huyện Tân Châu', 'created_at' => $now],
                [ 'id' => '231', 'ma_quanhuyen' => '47008', 'ten_quanhuyen' => 'Huyện Trảng Bàng', 'created_at' => $now],
                [ 'id' => '232', 'ma_quanhuyen' => '47009', 'ten_quanhuyen' => 'Thị xã Tây Ninh', 'created_at' => $now],
                [ 'id' => '233', 'ma_quanhuyen' => '48001', 'ten_quanhuyen' => 'Huyện Bến Cát', 'created_at' => $now],
                [ 'id' => '234', 'ma_quanhuyen' => '48002', 'ten_quanhuyen' => 'Huyện Dầu tiếng', 'created_at' => $now],
                [ 'id' => '235', 'ma_quanhuyen' => '48003', 'ten_quanhuyen' => 'Huyện Dĩ An', 'created_at' => $now],
                [ 'id' => '236', 'ma_quanhuyen' => '48004', 'ten_quanhuyen' => 'Huyện Phú Giáo', 'created_at' => $now],
                [ 'id' => '237', 'ma_quanhuyen' => '48005', 'ten_quanhuyen' => 'Huyện Tân Uyên', 'created_at' => $now],
                [ 'id' => '238', 'ma_quanhuyen' => '48006', 'ten_quanhuyen' => 'Huyện Thuận An', 'created_at' => $now],
                [ 'id' => '239', 'ma_quanhuyen' => '48007', 'ten_quanhuyen' => 'Thị xã Thủ Dầu Một', 'created_at' => $now],
                [ 'id' => '240', 'ma_quanhuyen' => '49001', 'ten_quanhuyen' => 'Huyện Cẩm Mỹ', 'created_at' => $now],
                [ 'id' => '241', 'ma_quanhuyen' => '49002', 'ten_quanhuyen' => 'Huyện Định Quán', 'created_at' => $now],
                [ 'id' => '242', 'ma_quanhuyen' => '49003', 'ten_quanhuyen' => 'Huyện Long Thành', 'created_at' => $now],
                [ 'id' => '243', 'ma_quanhuyen' => '49004', 'ten_quanhuyen' => 'Huyện Nhơn Trạch', 'created_at' => $now],
                [ 'id' => '244', 'ma_quanhuyen' => '49005', 'ten_quanhuyen' => 'Huyện Tân Phú', 'created_at' => $now],
                [ 'id' => '245', 'ma_quanhuyen' => '49006', 'ten_quanhuyen' => 'Huyện Thống Nhất', 'created_at' => $now],
                [ 'id' => '246', 'ma_quanhuyen' => '49007', 'ten_quanhuyen' => 'Huyện Trảng Bom', 'created_at' => $now],
                [ 'id' => '247', 'ma_quanhuyen' => '49008', 'ten_quanhuyen' => 'Huyện Vĩnh Cửu', 'created_at' => $now],
                [ 'id' => '248', 'ma_quanhuyen' => '49009', 'ten_quanhuyen' => 'Huyện Xuân Lộc', 'created_at' => $now],
                [ 'id' => '249', 'ma_quanhuyen' => '49010', 'ten_quanhuyen' => 'Thành phố Biên Hòa', 'created_at' => $now],
                [ 'id' => '250', 'ma_quanhuyen' => '49011', 'ten_quanhuyen' => 'Thị xã Long Khánh', 'created_at' => $now],
                [ 'id' => '251', 'ma_quanhuyen' => '50001', 'ten_quanhuyen' => 'Huyện Côn Đảo', 'created_at' => $now],
                [ 'id' => '252', 'ma_quanhuyen' => '50002', 'ten_quanhuyen' => 'Huyện Châu Đức', 'created_at' => $now],
                [ 'id' => '253', 'ma_quanhuyen' => '50003', 'ten_quanhuyen' => 'Huyện Đất Đỏ', 'created_at' => $now],
                [ 'id' => '254', 'ma_quanhuyen' => '50004', 'ten_quanhuyen' => 'Huyện Long Điền', 'created_at' => $now],
                [ 'id' => '255', 'ma_quanhuyen' => '50005', 'ten_quanhuyen' => 'Huyện Tân Thành', 'created_at' => $now],
                [ 'id' => '256', 'ma_quanhuyen' => '50006', 'ten_quanhuyen' => 'Huyện Xuyên Mộc', 'created_at' => $now],
                [ 'id' => '257', 'ma_quanhuyen' => '50007', 'ten_quanhuyen' => 'Thành phố Vũng Tàu', 'created_at' => $now],
                [ 'id' => '258', 'ma_quanhuyen' => '50008', 'ten_quanhuyen' => 'Thị xã Bà Rịa', 'created_at' => $now],
                [ 'id' => '259', 'ma_quanhuyen' => '31001', 'ten_quanhuyen' => 'Huyện Cam Lộ', 'created_at' => $now],
                [ 'id' => '260', 'ma_quanhuyen' => '31002', 'ten_quanhuyen' => 'Huyện Đa Krông', 'created_at' => $now],
                [ 'id' => '261', 'ma_quanhuyen' => '31003', 'ten_quanhuyen' => 'Huyện Gio Linh', 'created_at' => $now],
                [ 'id' => '262', 'ma_quanhuyen' => '31004', 'ten_quanhuyen' => 'Huyện Hải Lăng', 'created_at' => $now],
                [ 'id' => '263', 'ma_quanhuyen' => '31005', 'ten_quanhuyen' => 'Huyện Hướng Hóa', 'created_at' => $now],
                [ 'id' => '264', 'ma_quanhuyen' => '31006', 'ten_quanhuyen' => 'Huyện Triệu Phong', 'created_at' => $now],
                [ 'id' => '265', 'ma_quanhuyen' => '31007', 'ten_quanhuyen' => 'Huyện Vĩnh Linh', 'created_at' => $now],
                [ 'id' => '266', 'ma_quanhuyen' => '31008', 'ten_quanhuyen' => 'Thành phố Đông Hà', 'created_at' => $now],
                [ 'id' => '267', 'ma_quanhuyen' => '31009', 'ten_quanhuyen' => 'Thị xã Quảng Trị', 'created_at' => $now],
                [ 'id' => '268', 'ma_quanhuyen' => '32001', 'ten_quanhuyen' => 'Huyện A Lưới', 'created_at' => $now],
                [ 'id' => '269', 'ma_quanhuyen' => '32002', 'ten_quanhuyen' => 'Huyện Hương Trà', 'created_at' => $now],
                [ 'id' => '270', 'ma_quanhuyen' => '32003', 'ten_quanhuyen' => 'Huyện Nam Đông', 'created_at' => $now],
                [ 'id' => '271', 'ma_quanhuyen' => '32004', 'ten_quanhuyen' => 'Huyện Phong Điền', 'created_at' => $now],
                [ 'id' => '272', 'ma_quanhuyen' => '32005', 'ten_quanhuyen' => 'Huyện Phú Lộc', 'created_at' => $now],
                [ 'id' => '273', 'ma_quanhuyen' => '32006', 'ten_quanhuyen' => 'Huyện Phú Vang', 'created_at' => $now],
                [ 'id' => '274', 'ma_quanhuyen' => '32007', 'ten_quanhuyen' => 'Huyện Quảng Điền', 'created_at' => $now],
                [ 'id' => '275', 'ma_quanhuyen' => '32008', 'ten_quanhuyen' => 'Thành phố Huế', 'created_at' => $now],
                [ 'id' => '276', 'ma_quanhuyen' => '32009', 'ten_quanhuyen' => 'Thị xã Hương Thủy', 'created_at' => $now],
                [ 'id' => '277', 'ma_quanhuyen' => '33101', 'ten_quanhuyen' => 'Huyện Hoà Vang', 'created_at' => $now],
                [ 'id' => '278', 'ma_quanhuyen' => '33102', 'ten_quanhuyen' => 'Huyện Hoàng Sa', 'created_at' => $now],
                [ 'id' => '279', 'ma_quanhuyen' => '33103', 'ten_quanhuyen' => 'Quân Cẩm Lệ', 'created_at' => $now],
                [ 'id' => '280', 'ma_quanhuyen' => '33104', 'ten_quanhuyen' => 'Quận Hải Châu', 'created_at' => $now],
                [ 'id' => '281', 'ma_quanhuyen' => '33105', 'ten_quanhuyen' => 'Quận Liên Chiểu', 'created_at' => $now],
                [ 'id' => '282', 'ma_quanhuyen' => '33106', 'ten_quanhuyen' => 'Quận Ngũ Hành Sơn', 'created_at' => $now],
                [ 'id' => '283', 'ma_quanhuyen' => '33107', 'ten_quanhuyen' => 'Quận Sơn Trà', 'created_at' => $now],
                [ 'id' => '284', 'ma_quanhuyen' => '33108', 'ten_quanhuyen' => 'Quận Thanh Khê', 'created_at' => $now],
                [ 'id' => '285', 'ma_quanhuyen' => '34001', 'ten_quanhuyen' => 'Huyện Bắc Trà My', 'created_at' => $now],
                [ 'id' => '286', 'ma_quanhuyen' => '34002', 'ten_quanhuyen' => 'Huyện Duy Xuyên', 'created_at' => $now],
                [ 'id' => '287', 'ma_quanhuyen' => '34003', 'ten_quanhuyen' => 'Huyện Đại Lộc', 'created_at' => $now],
                [ 'id' => '288', 'ma_quanhuyen' => '34004', 'ten_quanhuyen' => 'Huyện Điện Bàn', 'created_at' => $now],
                [ 'id' => '289', 'ma_quanhuyen' => '34005', 'ten_quanhuyen' => 'Huyện Đông Giang', 'created_at' => $now],
                [ 'id' => '290', 'ma_quanhuyen' => '34006', 'ten_quanhuyen' => 'Huyện Hiệp Đức', 'created_at' => $now],
                [ 'id' => '291', 'ma_quanhuyen' => '34007', 'ten_quanhuyen' => 'Huyện Nam Giang', 'created_at' => $now],
                [ 'id' => '292', 'ma_quanhuyen' => '34008', 'ten_quanhuyen' => 'Huyện Nam Trà My', 'created_at' => $now],
                [ 'id' => '293', 'ma_quanhuyen' => '34009', 'ten_quanhuyen' => 'Huyện Nông Sơn', 'created_at' => $now],
                [ 'id' => '294', 'ma_quanhuyen' => '34010', 'ten_quanhuyen' => 'Huyện Núi Thành', 'created_at' => $now],
                [ 'id' => '295', 'ma_quanhuyen' => '34011', 'ten_quanhuyen' => 'Huyện Phú Ninh', 'created_at' => $now],
                [ 'id' => '296', 'ma_quanhuyen' => '34012', 'ten_quanhuyen' => 'Huyện Phước Sơn', 'created_at' => $now],
                [ 'id' => '297', 'ma_quanhuyen' => '34013', 'ten_quanhuyen' => 'Huyện Quế Sơn', 'created_at' => $now],
                [ 'id' => '298', 'ma_quanhuyen' => '34014', 'ten_quanhuyen' => 'Huyện Tây Giang', 'created_at' => $now],
                [ 'id' => '299', 'ma_quanhuyen' => '34015', 'ten_quanhuyen' => 'Huyện Tiên Phước', 'created_at' => $now],
                [ 'id' => '300', 'ma_quanhuyen' => '34016', 'ten_quanhuyen' => 'Huyện Thăng Bình', 'created_at' => $now],
                [ 'id' => '301', 'ma_quanhuyen' => '34017', 'ten_quanhuyen' => 'Thành phố Hội An', 'created_at' => $now],
                [ 'id' => '302', 'ma_quanhuyen' => '34018', 'ten_quanhuyen' => 'Thành phố Tam Kỳ', 'created_at' => $now],
                [ 'id' => '303', 'ma_quanhuyen' => '35001', 'ten_quanhuyen' => 'Huyện Ba Tơ', 'created_at' => $now],
                [ 'id' => '304', 'ma_quanhuyen' => '35002', 'ten_quanhuyen' => 'Huyện Bình Sơn', 'created_at' => $now],
                [ 'id' => '305', 'ma_quanhuyen' => '35003', 'ten_quanhuyen' => 'Huyện Đức Phổ', 'created_at' => $now],
                [ 'id' => '306', 'ma_quanhuyen' => '35004', 'ten_quanhuyen' => 'Huyện Lý Sơn', 'created_at' => $now],
                [ 'id' => '307', 'ma_quanhuyen' => '35005', 'ten_quanhuyen' => 'Huyện Minh Long', 'created_at' => $now],
                [ 'id' => '308', 'ma_quanhuyen' => '35006', 'ten_quanhuyen' => 'Huyện Mộ Đức', 'created_at' => $now],
                [ 'id' => '309', 'ma_quanhuyen' => '35007', 'ten_quanhuyen' => 'Huyện Nghĩa Hành', 'created_at' => $now],
                [ 'id' => '310', 'ma_quanhuyen' => '35008', 'ten_quanhuyen' => 'Huyện Sơn Hà', 'created_at' => $now],
                [ 'id' => '311', 'ma_quanhuyen' => '35009', 'ten_quanhuyen' => 'Huyện Sơn Tây', 'created_at' => $now],
                [ 'id' => '312', 'ma_quanhuyen' => '35010', 'ten_quanhuyen' => 'Huyện Sơn Tịnh', 'created_at' => $now],
                [ 'id' => '313', 'ma_quanhuyen' => '35011', 'ten_quanhuyen' => 'Huyên Tây Trà', 'created_at' => $now],
                [ 'id' => '314', 'ma_quanhuyen' => '35012', 'ten_quanhuyen' => 'Huyện Tư Nghĩa', 'created_at' => $now],
                [ 'id' => '315', 'ma_quanhuyen' => '35013', 'ten_quanhuyen' => 'Huyện Trà Bồng', 'created_at' => $now],
                [ 'id' => '316', 'ma_quanhuyen' => '35014', 'ten_quanhuyen' => 'Thành phố Quảng Ngãi', 'created_at' => $now],
                [ 'id' => '317', 'ma_quanhuyen' => '36101', 'ten_quanhuyen' => 'Huyện An Lão', 'created_at' => $now],
                [ 'id' => '318', 'ma_quanhuyen' => '36102', 'ten_quanhuyen' => 'Huyện An Nhơn', 'created_at' => $now],
                [ 'id' => '319', 'ma_quanhuyen' => '36103', 'ten_quanhuyen' => 'Huyện Hoài Ân', 'created_at' => $now],
                [ 'id' => '320', 'ma_quanhuyen' => '36104', 'ten_quanhuyen' => 'Huyện Hoài Nhơn', 'created_at' => $now],
                [ 'id' => '321', 'ma_quanhuyen' => '36105', 'ten_quanhuyen' => 'Huyện Phù Cát', 'created_at' => $now],
                [ 'id' => '322', 'ma_quanhuyen' => '36106', 'ten_quanhuyen' => 'Huyện Phù Mỹ', 'created_at' => $now],
                [ 'id' => '323', 'ma_quanhuyen' => '36107', 'ten_quanhuyen' => 'Huyện Tây Sơn', 'created_at' => $now],
                [ 'id' => '324', 'ma_quanhuyen' => '36108', 'ten_quanhuyen' => 'Huyện Tuy Phước', 'created_at' => $now],
                [ 'id' => '325', 'ma_quanhuyen' => '36109', 'ten_quanhuyen' => 'Huyện Vân Canh', 'created_at' => $now],
                [ 'id' => '326', 'ma_quanhuyen' => '36110', 'ten_quanhuyen' => 'Huyện Vĩnh Thạnh', 'created_at' => $now],
                [ 'id' => '327', 'ma_quanhuyen' => '36111', 'ten_quanhuyen' => 'Thành phố Qui Nhơn', 'created_at' => $now],
                [ 'id' => '328', 'ma_quanhuyen' => '37001', 'ten_quanhuyen' => 'Huyện Đông Hoà', 'created_at' => $now],
                [ 'id' => '329', 'ma_quanhuyen' => '37002', 'ten_quanhuyen' => 'Huyện Đồng Xuân', 'created_at' => $now],
                [ 'id' => '330', 'ma_quanhuyen' => '37003', 'ten_quanhuyen' => 'Huyện Phú Hoà', 'created_at' => $now],
                [ 'id' => '331', 'ma_quanhuyen' => '37004', 'ten_quanhuyen' => 'Huyện Sông Hinh', 'created_at' => $now],
                [ 'id' => '332', 'ma_quanhuyen' => '37005', 'ten_quanhuyen' => 'Huyện Sơn Hòa', 'created_at' => $now],
                [ 'id' => '333', 'ma_quanhuyen' => '37006', 'ten_quanhuyen' => 'Huyện Tuy An', 'created_at' => $now],
                [ 'id' => '334', 'ma_quanhuyen' => '37007', 'ten_quanhuyen' => 'Huyện Tuy Hòa', 'created_at' => $now],
                [ 'id' => '335', 'ma_quanhuyen' => '37008', 'ten_quanhuyen' => 'Thành phố Tuy Hoà', 'created_at' => $now],
                [ 'id' => '336', 'ma_quanhuyen' => '37009', 'ten_quanhuyen' => 'Thị xã Sông Cầu', 'created_at' => $now],
                [ 'id' => '337', 'ma_quanhuyen' => '39001', 'ten_quanhuyen' => 'Huyện Cam Lâm', 'created_at' => $now],
                [ 'id' => '338', 'ma_quanhuyen' => '39002', 'ten_quanhuyen' => 'Huyện Diên Khánh', 'created_at' => $now],
                [ 'id' => '339', 'ma_quanhuyen' => '39003', 'ten_quanhuyen' => 'Huyện Khánh Sơn', 'created_at' => $now],
                [ 'id' => '340', 'ma_quanhuyen' => '39004', 'ten_quanhuyen' => 'Huyện Khánh Vĩnh', 'created_at' => $now],
                [ 'id' => '341', 'ma_quanhuyen' => '39005', 'ten_quanhuyen' => 'Huyện Ninh Hòa', 'created_at' => $now],
                [ 'id' => '342', 'ma_quanhuyen' => '39006', 'ten_quanhuyen' => 'Huyện Trường Sa', 'created_at' => $now],
                [ 'id' => '343', 'ma_quanhuyen' => '39007', 'ten_quanhuyen' => 'Huyện Vạn Ninh', 'created_at' => $now],
                [ 'id' => '344', 'ma_quanhuyen' => '39008', 'ten_quanhuyen' => 'Thành phố Cam Ranh', 'created_at' => $now],
                [ 'id' => '345', 'ma_quanhuyen' => '39009', 'ten_quanhuyen' => 'Thành phố Nha Trang', 'created_at' => $now],
                [ 'id' => '346', 'ma_quanhuyen' => '40001', 'ten_quanhuyen' => 'Huyện Bắc Bình', 'created_at' => $now],
                [ 'id' => '347', 'ma_quanhuyen' => '40002', 'ten_quanhuyen' => 'Huyện Đức Linh', 'created_at' => $now],
                [ 'id' => '348', 'ma_quanhuyen' => '40003', 'ten_quanhuyen' => 'Huyện Hàm Tân', 'created_at' => $now],
                [ 'id' => '349', 'ma_quanhuyen' => '40004', 'ten_quanhuyen' => 'Huyện Hàm Thuận Bắc', 'created_at' => $now],
                [ 'id' => '350', 'ma_quanhuyen' => '40005', 'ten_quanhuyen' => 'Huyện Hàm Thuận Nam', 'created_at' => $now],
                [ 'id' => '351', 'ma_quanhuyen' => '40006', 'ten_quanhuyen' => 'Huyện Phú Qúy', 'created_at' => $now],
                [ 'id' => '352', 'ma_quanhuyen' => '40007', 'ten_quanhuyen' => 'Huyện Tánh Linh', 'created_at' => $now],
                [ 'id' => '353', 'ma_quanhuyen' => '40008', 'ten_quanhuyen' => 'Huyện Tuy Phong', 'created_at' => $now],
                [ 'id' => '354', 'ma_quanhuyen' => '40009', 'ten_quanhuyen' => 'Thành phố Phan Thiết', 'created_at' => $now],
                [ 'id' => '355', 'ma_quanhuyen' => '40010', 'ten_quanhuyen' => 'Thị xã La Gi', 'created_at' => $now],
                [ 'id' => '356', 'ma_quanhuyen' => '20001', 'ten_quanhuyen' => 'Huyện Bình Giang', 'created_at' => $now],
                [ 'id' => '357', 'ma_quanhuyen' => '20002', 'ten_quanhuyen' => 'Huyện Cẩm Giàng', 'created_at' => $now],
                [ 'id' => '358', 'ma_quanhuyen' => '20003', 'ten_quanhuyen' => 'Huyện Gia Lộc', 'created_at' => $now],
                [ 'id' => '359', 'ma_quanhuyen' => '20004', 'ten_quanhuyen' => 'Huyện Kim Thành', 'created_at' => $now],
                [ 'id' => '360', 'ma_quanhuyen' => '20005', 'ten_quanhuyen' => 'Huyện Kinh Môn', 'created_at' => $now],
                [ 'id' => '361', 'ma_quanhuyen' => '20006', 'ten_quanhuyen' => 'Huyện Nam Sách', 'created_at' => $now],
                [ 'id' => '362', 'ma_quanhuyen' => '20007', 'ten_quanhuyen' => 'Huyện Ninh Giang', 'created_at' => $now],
                [ 'id' => '363', 'ma_quanhuyen' => '20008', 'ten_quanhuyen' => 'Huyện Tứ Kỳ', 'created_at' => $now],
                [ 'id' => '364', 'ma_quanhuyen' => '20009', 'ten_quanhuyen' => 'Huyện Thanh Hà', 'created_at' => $now],
                [ 'id' => '365', 'ma_quanhuyen' => '20010', 'ten_quanhuyen' => 'Huyện Thanh Miện', 'created_at' => $now],
                [ 'id' => '366', 'ma_quanhuyen' => '20011', 'ten_quanhuyen' => 'Thành phố Hải Dương', 'created_at' => $now],
                [ 'id' => '367', 'ma_quanhuyen' => '20012', 'ten_quanhuyen' => 'Thị xã Chí Linh', 'created_at' => $now],
                [ 'id' => '368', 'ma_quanhuyen' => '21001', 'ten_quanhuyen' => 'Huyện An Dương', 'created_at' => $now],
                [ 'id' => '369', 'ma_quanhuyen' => '21002', 'ten_quanhuyen' => 'Huyện An Lão', 'created_at' => $now],
                [ 'id' => '370', 'ma_quanhuyen' => '21003', 'ten_quanhuyen' => 'Huyện Bạch Long Vĩ', 'created_at' => $now],
                [ 'id' => '371', 'ma_quanhuyen' => '21004', 'ten_quanhuyen' => 'Huyện Cát Hải', 'created_at' => $now],
                [ 'id' => '372', 'ma_quanhuyen' => '21005', 'ten_quanhuyen' => 'Huyện Kiến Thụy', 'created_at' => $now],
                [ 'id' => '373', 'ma_quanhuyen' => '21006', 'ten_quanhuyen' => 'Huyện Tiên Lãng', 'created_at' => $now],
                [ 'id' => '374', 'ma_quanhuyen' => '21007', 'ten_quanhuyen' => 'Huyện Thuỷ Nguyên', 'created_at' => $now],
                [ 'id' => '375', 'ma_quanhuyen' => '21008', 'ten_quanhuyen' => 'Huyện Vĩnh Bảo', 'created_at' => $now],
                [ 'id' => '376', 'ma_quanhuyen' => '21009', 'ten_quanhuyen' => 'Quận Hải An', 'created_at' => $now],
                [ 'id' => '377', 'ma_quanhuyen' => '21010', 'ten_quanhuyen' => 'Quận Hồng Bàng', 'created_at' => $now],
                [ 'id' => '378', 'ma_quanhuyen' => '21011', 'ten_quanhuyen' => 'Quận Kiến An', 'created_at' => $now],
                [ 'id' => '379', 'ma_quanhuyen' => '21012', 'ten_quanhuyen' => 'Quận Lê Chân', 'created_at' => $now],
                [ 'id' => '380', 'ma_quanhuyen' => '21013', 'ten_quanhuyen' => 'Quận Ngô Quyền', 'created_at' => $now],
                [ 'id' => '381', 'ma_quanhuyen' => '21014', 'ten_quanhuyen' => 'Thị xã Đồ Sơn', 'created_at' => $now],
                [ 'id' => '382', 'ma_quanhuyen' => '22101', 'ten_quanhuyen' => 'Huyện Ân Thi', 'created_at' => $now],
                [ 'id' => '383', 'ma_quanhuyen' => '22102', 'ten_quanhuyen' => 'Huyện Kim Động', 'created_at' => $now],
                [ 'id' => '384', 'ma_quanhuyen' => '22103', 'ten_quanhuyen' => 'Huyện Khoái Châu', 'created_at' => $now],
                [ 'id' => '385', 'ma_quanhuyen' => '22104', 'ten_quanhuyen' => 'Huyện Mỹ Hào', 'created_at' => $now],
                [ 'id' => '386', 'ma_quanhuyen' => '22105', 'ten_quanhuyen' => 'Huyện Phù Cơ', 'created_at' => $now],
                [ 'id' => '387', 'ma_quanhuyen' => '22106', 'ten_quanhuyen' => 'Huyện Tiên Lữ', 'created_at' => $now],
                [ 'id' => '388', 'ma_quanhuyen' => '22107', 'ten_quanhuyen' => 'Huyện Văn Giang', 'created_at' => $now],
                [ 'id' => '389', 'ma_quanhuyen' => '22108', 'ten_quanhuyen' => 'Huyện Văn Lâm', 'created_at' => $now],
                [ 'id' => '390', 'ma_quanhuyen' => '22109', 'ten_quanhuyen' => 'Huyện Yên Mỹ', 'created_at' => $now],
                [ 'id' => '391', 'ma_quanhuyen' => '22110', 'ten_quanhuyen' => 'Thành phố Hưng Yên', 'created_at' => $now],
                [ 'id' => '392', 'ma_quanhuyen' => '23001', 'ten_quanhuyen' => 'Huyện Đông Hưng', 'created_at' => $now],
                [ 'id' => '393', 'ma_quanhuyen' => '23002', 'ten_quanhuyen' => 'Huyện Hưng Hà', 'created_at' => $now],
                [ 'id' => '394', 'ma_quanhuyen' => '23003', 'ten_quanhuyen' => 'Huyện Kiến Xương', 'created_at' => $now],
                [ 'id' => '395', 'ma_quanhuyen' => '23004', 'ten_quanhuyen' => 'Huyện Quỳnh Phụ', 'created_at' => $now],
                [ 'id' => '396', 'ma_quanhuyen' => '23005', 'ten_quanhuyen' => 'Huyện Tiền Hải', 'created_at' => $now],
                [ 'id' => '397', 'ma_quanhuyen' => '23006', 'ten_quanhuyen' => 'Huyện Thái Thụy', 'created_at' => $now],
                [ 'id' => '398', 'ma_quanhuyen' => '23007', 'ten_quanhuyen' => 'Huyện Vũ Thư', 'created_at' => $now],
                [ 'id' => '399', 'ma_quanhuyen' => '23008', 'ten_quanhuyen' => 'Thành phố Thái Bình', 'created_at' => $now],
                [ 'id' => '400', 'ma_quanhuyen' => '24101', 'ten_quanhuyen' => 'Huyện Bình Lục', 'created_at' => $now],
                [ 'id' => '401', 'ma_quanhuyen' => '24102', 'ten_quanhuyen' => 'Huyện Duy Tiên', 'created_at' => $now],
                [ 'id' => '402', 'ma_quanhuyen' => '24103', 'ten_quanhuyen' => 'Huyện Kim Bảng', 'created_at' => $now],
                [ 'id' => '403', 'ma_quanhuyen' => '24104', 'ten_quanhuyen' => 'Huyện Lý Nhân', 'created_at' => $now],
                [ 'id' => '404', 'ma_quanhuyen' => '24105', 'ten_quanhuyen' => 'Huyện Thanh Liêm', 'created_at' => $now],
                [ 'id' => '405', 'ma_quanhuyen' => '24106', 'ten_quanhuyen' => 'Thành phố Phủ Lý', 'created_at' => $now],
                [ 'id' => '406', 'ma_quanhuyen' => '25001', 'ten_quanhuyen' => 'Huyện Giao Thủy', 'created_at' => $now],
                [ 'id' => '407', 'ma_quanhuyen' => '25002', 'ten_quanhuyen' => 'Huyện Hải Hậu', 'created_at' => $now],
                [ 'id' => '408', 'ma_quanhuyen' => '25003', 'ten_quanhuyen' => 'Huyện Mỹ Lộc', 'created_at' => $now],
                [ 'id' => '409', 'ma_quanhuyen' => '25004', 'ten_quanhuyen' => 'Huyện Nam Trực', 'created_at' => $now],
                [ 'id' => '410', 'ma_quanhuyen' => '25005', 'ten_quanhuyen' => 'Huyện Nghĩa Hưng', 'created_at' => $now],
                [ 'id' => '411', 'ma_quanhuyen' => '25006', 'ten_quanhuyen' => 'Huyện Trực Ninh', 'created_at' => $now],
                [ 'id' => '412', 'ma_quanhuyen' => '25007', 'ten_quanhuyen' => 'Huyện Vụ Bản', 'created_at' => $now],
                [ 'id' => '413', 'ma_quanhuyen' => '25008', 'ten_quanhuyen' => 'Huyện Xuân Trường', 'created_at' => $now],
                [ 'id' => '414', 'ma_quanhuyen' => '25009', 'ten_quanhuyen' => 'Huyện Ý Yên', 'created_at' => $now],
                [ 'id' => '415', 'ma_quanhuyen' => '25010', 'ten_quanhuyen' => 'Thành phố Nam Định', 'created_at' => $now],
                [ 'id' => '416', 'ma_quanhuyen' => '26101', 'ten_quanhuyen' => 'Huyện Gia Viễn', 'created_at' => $now],
                [ 'id' => '417', 'ma_quanhuyen' => '26102', 'ten_quanhuyen' => 'Huyện Hoa Lư', 'created_at' => $now],
                [ 'id' => '418', 'ma_quanhuyen' => '26103', 'ten_quanhuyen' => 'Huyện Kim Sơn', 'created_at' => $now],
                [ 'id' => '419', 'ma_quanhuyen' => '26104', 'ten_quanhuyen' => 'Huyện Nho Quan', 'created_at' => $now],
                [ 'id' => '420', 'ma_quanhuyen' => '26105', 'ten_quanhuyen' => 'Huyện Yên Khánh', 'created_at' => $now],
                [ 'id' => '421', 'ma_quanhuyen' => '26106', 'ten_quanhuyen' => 'Huyện Yên Mô', 'created_at' => $now],
                [ 'id' => '422', 'ma_quanhuyen' => '26107', 'ten_quanhuyen' => 'Thành phố Ninh Bình', 'created_at' => $now],
                [ 'id' => '423', 'ma_quanhuyen' => '26108', 'ten_quanhuyen' => 'Thị xã Tam Điệp', 'created_at' => $now],
                [ 'id' => '424', 'ma_quanhuyen' => '27001', 'ten_quanhuyen' => 'Huyện Bá Thước', 'created_at' => $now],
                [ 'id' => '425', 'ma_quanhuyen' => '27002', 'ten_quanhuyen' => 'Huyện Cẩm Thủy', 'created_at' => $now],
                [ 'id' => '426', 'ma_quanhuyen' => '27003', 'ten_quanhuyen' => 'Huyện Đông Sơn', 'created_at' => $now],
                [ 'id' => '427', 'ma_quanhuyen' => '27004', 'ten_quanhuyen' => 'Huyện Hà Trung', 'created_at' => $now],
                [ 'id' => '428', 'ma_quanhuyen' => '27005', 'ten_quanhuyen' => 'Huyện Hậu Lộc', 'created_at' => $now],
                [ 'id' => '429', 'ma_quanhuyen' => '27006', 'ten_quanhuyen' => 'Huyện Hoằng Hóa', 'created_at' => $now],
                [ 'id' => '430', 'ma_quanhuyen' => '27007', 'ten_quanhuyen' => 'Huyện Lang Chánh', 'created_at' => $now],
                [ 'id' => '431', 'ma_quanhuyen' => '27008', 'ten_quanhuyen' => 'Huyện Mường Lát', 'created_at' => $now],
                [ 'id' => '432', 'ma_quanhuyen' => '27009', 'ten_quanhuyen' => 'Huyện Nông Cống', 'created_at' => $now],
                [ 'id' => '433', 'ma_quanhuyen' => '27010', 'ten_quanhuyen' => 'Huyện Nga Sơn', 'created_at' => $now],
                [ 'id' => '434', 'ma_quanhuyen' => '27011', 'ten_quanhuyen' => 'Huyện Ngọc Lạc', 'created_at' => $now],
                [ 'id' => '435', 'ma_quanhuyen' => '27012', 'ten_quanhuyen' => 'Huyện Như Thanh', 'created_at' => $now],
                [ 'id' => '436', 'ma_quanhuyen' => '27013', 'ten_quanhuyen' => 'Huyện Như Xuân', 'created_at' => $now],
                [ 'id' => '437', 'ma_quanhuyen' => '27014', 'ten_quanhuyen' => 'Huyện Quan Hóa', 'created_at' => $now],
                [ 'id' => '438', 'ma_quanhuyen' => '27015', 'ten_quanhuyen' => 'Huyện Quan Sơn', 'created_at' => $now],
                [ 'id' => '439', 'ma_quanhuyen' => '27016', 'ten_quanhuyen' => 'Huyện Quảng Xương', 'created_at' => $now],
                [ 'id' => '440', 'ma_quanhuyen' => '27017', 'ten_quanhuyen' => 'Huyện Tĩnh Gia', 'created_at' => $now],
                [ 'id' => '441', 'ma_quanhuyen' => '27018', 'ten_quanhuyen' => 'Huyện Thạch Thành', 'created_at' => $now],
                [ 'id' => '442', 'ma_quanhuyen' => '27020', 'ten_quanhuyen' => 'Huyện Thiệu Hoá', 'created_at' => $now],
                [ 'id' => '443', 'ma_quanhuyen' => '27021', 'ten_quanhuyen' => 'Huyện Thọ Xuân', 'created_at' => $now],
                [ 'id' => '444', 'ma_quanhuyen' => '27022', 'ten_quanhuyen' => 'Huyện Thường Xuân', 'created_at' => $now],
                [ 'id' => '445', 'ma_quanhuyen' => '27023', 'ten_quanhuyen' => 'Huyện Triệu Sơn', 'created_at' => $now],
                [ 'id' => '446', 'ma_quanhuyen' => '27024', 'ten_quanhuyen' => 'Huyện Vĩnh Lộc', 'created_at' => $now],
                [ 'id' => '447', 'ma_quanhuyen' => '27025', 'ten_quanhuyen' => 'Huyện Yên Định', 'created_at' => $now],
                [ 'id' => '448', 'ma_quanhuyen' => '27026', 'ten_quanhuyen' => 'Thành phố Thanh Hóa', 'created_at' => $now],
                [ 'id' => '449', 'ma_quanhuyen' => '27027', 'ten_quanhuyen' => 'Thị xã Bỉm Sơn', 'created_at' => $now],
                [ 'id' => '450', 'ma_quanhuyen' => '27028', 'ten_quanhuyen' => 'Thị xã Sầm Sơn', 'created_at' => $now],
                [ 'id' => '451', 'ma_quanhuyen' => '28001', 'ten_quanhuyen' => 'Huyện Anh Sơn', 'created_at' => $now],
                [ 'id' => '452', 'ma_quanhuyen' => '28002', 'ten_quanhuyen' => 'Huyện Con Cuông', 'created_at' => $now],
                [ 'id' => '453', 'ma_quanhuyen' => '28003', 'ten_quanhuyen' => 'Huyện Diễn Châu', 'created_at' => $now],
                [ 'id' => '454', 'ma_quanhuyen' => '28004', 'ten_quanhuyen' => 'Huyện Đô Lương', 'created_at' => $now],
                [ 'id' => '455', 'ma_quanhuyen' => '28005', 'ten_quanhuyen' => 'Huyện Hưng Nguyên', 'created_at' => $now],
                [ 'id' => '456', 'ma_quanhuyen' => '28006', 'ten_quanhuyen' => 'Huyện Kỳ Sơn', 'created_at' => $now],
                [ 'id' => '457', 'ma_quanhuyen' => '28007', 'ten_quanhuyen' => 'Huyện Nam Đàn', 'created_at' => $now],
                [ 'id' => '458', 'ma_quanhuyen' => '28008', 'ten_quanhuyen' => 'Huyện Nghi Lộc', 'created_at' => $now],
                [ 'id' => '459', 'ma_quanhuyen' => '28009', 'ten_quanhuyen' => 'Huyện Nghĩa Đàn', 'created_at' => $now],
                [ 'id' => '460', 'ma_quanhuyen' => '28010', 'ten_quanhuyen' => 'Huyện Quế Phong', 'created_at' => $now],
                [ 'id' => '461', 'ma_quanhuyen' => '28011', 'ten_quanhuyen' => 'Huyện Quỳ Châu', 'created_at' => $now],
                [ 'id' => '462', 'ma_quanhuyen' => '28012', 'ten_quanhuyen' => 'Huyện Quỳ Hợp', 'created_at' => $now],
                [ 'id' => '463', 'ma_quanhuyen' => '28013', 'ten_quanhuyen' => 'Huyện Quỳnh Lưu', 'created_at' => $now],
                [ 'id' => '464', 'ma_quanhuyen' => '28014', 'ten_quanhuyen' => 'Huyện Tân Kỳ', 'created_at' => $now],
                [ 'id' => '465', 'ma_quanhuyen' => '28015', 'ten_quanhuyen' => 'Huyện Tương Dương', 'created_at' => $now],
                [ 'id' => '466', 'ma_quanhuyen' => '28016', 'ten_quanhuyen' => 'Huyện Thanh Chương', 'created_at' => $now],
                [ 'id' => '467', 'ma_quanhuyen' => '28017', 'ten_quanhuyen' => 'Huyện Yên Thành', 'created_at' => $now],
                [ 'id' => '468', 'ma_quanhuyen' => '28018', 'ten_quanhuyen' => 'Thành phố Vinh', 'created_at' => $now],
                [ 'id' => '469', 'ma_quanhuyen' => '28020', 'ten_quanhuyen' => 'Thị xã Cửa Lò', 'created_at' => $now],
                [ 'id' => '470', 'ma_quanhuyen' => '29001', 'ten_quanhuyen' => 'Huyện Can Lộc', 'created_at' => $now],
                [ 'id' => '471', 'ma_quanhuyen' => '29002', 'ten_quanhuyen' => 'Huyện Cẩm Xuyên', 'created_at' => $now],
                [ 'id' => '472', 'ma_quanhuyen' => '29003', 'ten_quanhuyen' => 'Huyện Đức Thọ', 'created_at' => $now],
                [ 'id' => '473', 'ma_quanhuyen' => '29004', 'ten_quanhuyen' => 'Huyện Hương Khê', 'created_at' => $now],
                [ 'id' => '474', 'ma_quanhuyen' => '29005', 'ten_quanhuyen' => 'Huyện Hương Sơn', 'created_at' => $now],
                [ 'id' => '475', 'ma_quanhuyen' => '29006', 'ten_quanhuyen' => 'Huyện Kỳ Anh', 'created_at' => $now],
                [ 'id' => '476', 'ma_quanhuyen' => '29007', 'ten_quanhuyen' => 'Huyện Lộc Hà', 'created_at' => $now],
                [ 'id' => '477', 'ma_quanhuyen' => '29008', 'ten_quanhuyen' => 'Huyện Nghi Xuân', 'created_at' => $now],
                [ 'id' => '478', 'ma_quanhuyen' => '29009', 'ten_quanhuyen' => 'Huyện Thạch Hà', 'created_at' => $now],
                [ 'id' => '479', 'ma_quanhuyen' => '29010', 'ten_quanhuyen' => 'Huyện Vũ Quang', 'created_at' => $now],
                [ 'id' => '480', 'ma_quanhuyen' => '29011', 'ten_quanhuyen' => 'Thành phố Hà Tĩnh', 'created_at' => $now],
                [ 'id' => '481', 'ma_quanhuyen' => '29012', 'ten_quanhuyen' => 'Thị xã Hồng Lĩnh', 'created_at' => $now],
                [ 'id' => '482', 'ma_quanhuyen' => '30001', 'ten_quanhuyen' => 'Huyện Bố Trạch', 'created_at' => $now],
                [ 'id' => '483', 'ma_quanhuyen' => '30002', 'ten_quanhuyen' => 'Huyện Lệ Thủy', 'created_at' => $now],
                [ 'id' => '484', 'ma_quanhuyen' => '30003', 'ten_quanhuyen' => 'Huyện Minh Hóa', 'created_at' => $now],
                [ 'id' => '485', 'ma_quanhuyen' => '30004', 'ten_quanhuyen' => 'Huyện Quảng Ninh', 'created_at' => $now],
                [ 'id' => '486', 'ma_quanhuyen' => '30005', 'ten_quanhuyen' => 'Huyện Quảng Trạch', 'created_at' => $now],
                [ 'id' => '487', 'ma_quanhuyen' => '30006', 'ten_quanhuyen' => 'Huyện Tuyên Hóa', 'created_at' => $now],
                [ 'id' => '488', 'ma_quanhuyen' => '30007', 'ten_quanhuyen' => 'Thị xã Đồng Hới', 'created_at' => $now],
                [ 'id' => '489', 'ma_quanhuyen' => '10001', 'ten_quanhuyen' => 'Huyện Bắc Yên', 'created_at' => $now],
                [ 'id' => '490', 'ma_quanhuyen' => '10002', 'ten_quanhuyen' => 'Huyện Mai Sơn', 'created_at' => $now],
                [ 'id' => '491', 'ma_quanhuyen' => '10003', 'ten_quanhuyen' => 'Huyện Mộc Châu', 'created_at' => $now],
                [ 'id' => '492', 'ma_quanhuyen' => '10004', 'ten_quanhuyen' => 'Huyện Mường La', 'created_at' => $now],
                [ 'id' => '493', 'ma_quanhuyen' => '10005', 'ten_quanhuyen' => 'Huyện Phù Yên', 'created_at' => $now],
                [ 'id' => '494', 'ma_quanhuyen' => '10006', 'ten_quanhuyen' => 'Huyện Quỳnh Nhai', 'created_at' => $now],
                [ 'id' => '495', 'ma_quanhuyen' => '10007', 'ten_quanhuyen' => 'Huyện Sông Mã', 'created_at' => $now],
                [ 'id' => '496', 'ma_quanhuyen' => '10008', 'ten_quanhuyen' => 'Huyện Sốp Cộp', 'created_at' => $now],
                [ 'id' => '497', 'ma_quanhuyen' => '10009', 'ten_quanhuyen' => 'Huyện Thuận Châu', 'created_at' => $now],
                [ 'id' => '498', 'ma_quanhuyen' => '10010', 'ten_quanhuyen' => 'Huyện Yên Châu', 'created_at' => $now],
                [ 'id' => '499', 'ma_quanhuyen' => '10011', 'ten_quanhuyen' => 'Thành phố Sơn La', 'created_at' => $now],
                [ 'id' => '500', 'ma_quanhuyen' => '11001', 'ten_quanhuyen' => 'Huyện Lục Yên', 'created_at' => $now],
                [ 'id' => '501', 'ma_quanhuyen' => '11002', 'ten_quanhuyen' => 'Huyện Mù Căng Chải', 'created_at' => $now],
                [ 'id' => '502', 'ma_quanhuyen' => '11003', 'ten_quanhuyen' => 'Huyện Trạm Tấu', 'created_at' => $now],
                [ 'id' => '503', 'ma_quanhuyen' => '11004', 'ten_quanhuyen' => 'Huyện Trấn Yên', 'created_at' => $now],
                [ 'id' => '504', 'ma_quanhuyen' => '11005', 'ten_quanhuyen' => 'Huyện Văn Chấn', 'created_at' => $now],
                [ 'id' => '505', 'ma_quanhuyen' => '11006', 'ten_quanhuyen' => 'Huyện Văn Yên', 'created_at' => $now],
                [ 'id' => '506', 'ma_quanhuyen' => '11007', 'ten_quanhuyen' => 'Huyện Yên Bình', 'created_at' => $now],
                [ 'id' => '507', 'ma_quanhuyen' => '11008', 'ten_quanhuyen' => 'Thành phố Yên Bái', 'created_at' => $now],
                [ 'id' => '508', 'ma_quanhuyen' => '11009', 'ten_quanhuyen' => 'Thị xã Nghĩa Lộ', 'created_at' => $now],
                [ 'id' => '509', 'ma_quanhuyen' => '12001', 'ten_quanhuyen' => 'Huyện Cao Phong', 'created_at' => $now],
                [ 'id' => '510', 'ma_quanhuyen' => '12002', 'ten_quanhuyen' => 'Huyện Đà Bắc', 'created_at' => $now],
                [ 'id' => '511', 'ma_quanhuyen' => '12003', 'ten_quanhuyen' => 'Huyện Kim Bôi', 'created_at' => $now],
                [ 'id' => '512', 'ma_quanhuyen' => '12004', 'ten_quanhuyen' => 'Huyện Kỳ Sơn', 'created_at' => $now],
                [ 'id' => '513', 'ma_quanhuyen' => '12005', 'ten_quanhuyen' => 'Huyện Lạc Sơn', 'created_at' => $now],
                [ 'id' => '514', 'ma_quanhuyen' => '12006', 'ten_quanhuyen' => 'Huyện Lạc Thủy', 'created_at' => $now],
                [ 'id' => '515', 'ma_quanhuyen' => '12007', 'ten_quanhuyen' => 'Huyện Lương Sơn', 'created_at' => $now],
                [ 'id' => '516', 'ma_quanhuyen' => '12008', 'ten_quanhuyen' => 'Huyện Mai Châu', 'created_at' => $now],
                [ 'id' => '517', 'ma_quanhuyen' => '12009', 'ten_quanhuyen' => 'Huyện Tân Lạc', 'created_at' => $now],
                [ 'id' => '518', 'ma_quanhuyen' => '12011', 'ten_quanhuyen' => 'Huyện Yên Thủy', 'created_at' => $now],
                [ 'id' => '519', 'ma_quanhuyen' => '12012', 'ten_quanhuyen' => 'Thành phố Hòa Bình', 'created_at' => $now],
                [ 'id' => '520', 'ma_quanhuyen' => '13111', 'ten_quanhuyen' => 'Huyện Đại Từ', 'created_at' => $now],
                [ 'id' => '521', 'ma_quanhuyen' => '13112', 'ten_quanhuyen' => 'Huyện Định Hóa', 'created_at' => $now],
                [ 'id' => '522', 'ma_quanhuyen' => '13103', 'ten_quanhuyen' => 'Huyện Đồng Hỷ', 'created_at' => $now],
                [ 'id' => '523', 'ma_quanhuyen' => '13104', 'ten_quanhuyen' => 'Huyện Phổ Yên', 'created_at' => $now],
                [ 'id' => '524', 'ma_quanhuyen' => '13105', 'ten_quanhuyen' => 'Huyện Phú Bình', 'created_at' => $now],
                [ 'id' => '525', 'ma_quanhuyen' => '13106', 'ten_quanhuyen' => 'Huyện Phú Lương', 'created_at' => $now],
                [ 'id' => '526', 'ma_quanhuyen' => '13107', 'ten_quanhuyen' => 'Huyện Võ Nhai', 'created_at' => $now],
                [ 'id' => '527', 'ma_quanhuyen' => '13108', 'ten_quanhuyen' => 'Thành phố Thái Nguyên', 'created_at' => $now],
                [ 'id' => '528', 'ma_quanhuyen' => '13109', 'ten_quanhuyen' => 'Thị xã Sông Công', 'created_at' => $now],
                [ 'id' => '529', 'ma_quanhuyen' => '14101', 'ten_quanhuyen' => 'Huyện Bắc Sơn', 'created_at' => $now],
                [ 'id' => '530', 'ma_quanhuyen' => '14102', 'ten_quanhuyen' => 'Huyện Bình Gia', 'created_at' => $now],
                [ 'id' => '531', 'ma_quanhuyen' => '14103', 'ten_quanhuyen' => 'Huyện Cao Lộc', 'created_at' => $now],
                [ 'id' => '532', 'ma_quanhuyen' => '14104', 'ten_quanhuyen' => 'Huyện Chi Lăng', 'created_at' => $now],
                [ 'id' => '533', 'ma_quanhuyen' => '14105', 'ten_quanhuyen' => 'Huyện Đình Lập', 'created_at' => $now],
                [ 'id' => '534', 'ma_quanhuyen' => '14106', 'ten_quanhuyen' => 'Huyện Hữu Lũng', 'created_at' => $now],
                [ 'id' => '535', 'ma_quanhuyen' => '14107', 'ten_quanhuyen' => 'Huyện Lộc Bình', 'created_at' => $now],
                [ 'id' => '536', 'ma_quanhuyen' => '14108', 'ten_quanhuyen' => 'Huyện Tràng Định', 'created_at' => $now],
                [ 'id' => '537', 'ma_quanhuyen' => '14109', 'ten_quanhuyen' => 'Huyện Văn Lãng', 'created_at' => $now],
                [ 'id' => '538', 'ma_quanhuyen' => '14110', 'ten_quanhuyen' => 'Huyện Văn Quan', 'created_at' => $now],
                [ 'id' => '539', 'ma_quanhuyen' => '14111', 'ten_quanhuyen' => 'Thành phố Lạng Sơn', 'created_at' => $now],
                [ 'id' => '540', 'ma_quanhuyen' => '15001', 'ten_quanhuyen' => 'Huyện Ba Chẽ', 'created_at' => $now],
                [ 'id' => '541', 'ma_quanhuyen' => '15002', 'ten_quanhuyen' => 'Huyện Bình Liêu', 'created_at' => $now],
                [ 'id' => '542', 'ma_quanhuyen' => '15003', 'ten_quanhuyen' => 'Huyện Cô Tô', 'created_at' => $now],
                [ 'id' => '543', 'ma_quanhuyen' => '15004', 'ten_quanhuyen' => 'Huyện Đầm Hà', 'created_at' => $now],
                [ 'id' => '544', 'ma_quanhuyen' => '15005', 'ten_quanhuyen' => 'Huyện Đông Triều', 'created_at' => $now],
                [ 'id' => '545', 'ma_quanhuyen' => '15006', 'ten_quanhuyen' => 'Huyện Hải Hà', 'created_at' => $now],
                [ 'id' => '546', 'ma_quanhuyen' => '15007', 'ten_quanhuyen' => 'Huyện Hoành Bồ', 'created_at' => $now],
                [ 'id' => '547', 'ma_quanhuyen' => '15008', 'ten_quanhuyen' => 'Huyện Tiên Yên', 'created_at' => $now],
                [ 'id' => '548', 'ma_quanhuyen' => '15009', 'ten_quanhuyen' => 'Huyện Vân Đồn', 'created_at' => $now],
                [ 'id' => '549', 'ma_quanhuyen' => '15010', 'ten_quanhuyen' => 'Huyện Yên Hưng', 'created_at' => $now],
                [ 'id' => '550', 'ma_quanhuyen' => '15011', 'ten_quanhuyen' => 'Thành phố Hạ Long', 'created_at' => $now],
                [ 'id' => '551', 'ma_quanhuyen' => '15013', 'ten_quanhuyen' => 'Thành phố Móng Cái', 'created_at' => $now],
                [ 'id' => '552', 'ma_quanhuyen' => '15014', 'ten_quanhuyen' => 'Thành phố Uông Bí', 'created_at' => $now],
                [ 'id' => '553', 'ma_quanhuyen' => '15015', 'ten_quanhuyen' => 'Thị xã Cẩm Phả', 'created_at' => $now],
                [ 'id' => '554', 'ma_quanhuyen' => '16101', 'ten_quanhuyen' => 'Huyện Hiệp Hòa', 'created_at' => $now],
                [ 'id' => '555', 'ma_quanhuyen' => '16102', 'ten_quanhuyen' => 'Huyện Lạng Giang', 'created_at' => $now],
                [ 'id' => '556', 'ma_quanhuyen' => '16103', 'ten_quanhuyen' => 'Huyện Lục Nam', 'created_at' => $now],
                [ 'id' => '557', 'ma_quanhuyen' => '16104', 'ten_quanhuyen' => 'Huyện Lục Ngạn', 'created_at' => $now],
                [ 'id' => '558', 'ma_quanhuyen' => '16105', 'ten_quanhuyen' => 'Huyện Sơn Động', 'created_at' => $now],
                [ 'id' => '559', 'ma_quanhuyen' => '16106', 'ten_quanhuyen' => 'Huyện Tân Yên', 'created_at' => $now],
                [ 'id' => '560', 'ma_quanhuyen' => '16107', 'ten_quanhuyen' => 'Huyện Việt Yên', 'created_at' => $now],
                [ 'id' => '561', 'ma_quanhuyen' => '16108', 'ten_quanhuyen' => 'Huyện Yên Dũng', 'created_at' => $now],
                [ 'id' => '562', 'ma_quanhuyen' => '16109', 'ten_quanhuyen' => 'Huyện Yên Thế', 'created_at' => $now],
                [ 'id' => '563', 'ma_quanhuyen' => '16110', 'ten_quanhuyen' => 'Thành phố Bắc Giang', 'created_at' => $now],
                [ 'id' => '564', 'ma_quanhuyen' => '17001', 'ten_quanhuyen' => 'Huyện Cẩm Khê', 'created_at' => $now],
                [ 'id' => '565', 'ma_quanhuyen' => '17002', 'ten_quanhuyen' => 'Huyện Đoan Hùng', 'created_at' => $now],
                [ 'id' => '566', 'ma_quanhuyen' => '17003', 'ten_quanhuyen' => 'Huyện Hạ Hoà', 'created_at' => $now],
                [ 'id' => '567', 'ma_quanhuyen' => '17004', 'ten_quanhuyen' => 'Huyện Lâm Thao', 'created_at' => $now],
                [ 'id' => '568', 'ma_quanhuyen' => '17005', 'ten_quanhuyen' => 'Huyện Phù Ninh', 'created_at' => $now],
                [ 'id' => '569', 'ma_quanhuyen' => '17006', 'ten_quanhuyen' => 'Huyện Tam Nông', 'created_at' => $now],
                [ 'id' => '570', 'ma_quanhuyen' => '17007', 'ten_quanhuyen' => 'Huyện Tân Sơn', 'created_at' => $now],
                [ 'id' => '571', 'ma_quanhuyen' => '17008', 'ten_quanhuyen' => 'Huyện Thanh Ba', 'created_at' => $now],
                [ 'id' => '572', 'ma_quanhuyen' => '17009', 'ten_quanhuyen' => 'Huyện Thanh Sơn', 'created_at' => $now],
                [ 'id' => '573', 'ma_quanhuyen' => '17010', 'ten_quanhuyen' => 'Huyện Thanh Thuỷ', 'created_at' => $now],
                [ 'id' => '574', 'ma_quanhuyen' => '17011', 'ten_quanhuyen' => 'Huyện Yên Lập', 'created_at' => $now],
                [ 'id' => '575', 'ma_quanhuyen' => '17012', 'ten_quanhuyen' => 'Thành phố Việt Trì', 'created_at' => $now],
                [ 'id' => '576', 'ma_quanhuyen' => '17013', 'ten_quanhuyen' => 'Thị xã Phú Thọ', 'created_at' => $now],
                [ 'id' => '577', 'ma_quanhuyen' => '18001', 'ten_quanhuyen' => 'Huyện Bình Xuyên', 'created_at' => $now],
                [ 'id' => '578', 'ma_quanhuyen' => '18002', 'ten_quanhuyen' => 'Huyện Lập Thạch', 'created_at' => $now],
                [ 'id' => '579', 'ma_quanhuyen' => '18003', 'ten_quanhuyen' => 'Huyện Sông Lô', 'created_at' => $now],
                [ 'id' => '580', 'ma_quanhuyen' => '18004', 'ten_quanhuyen' => 'Huyện Tam Dương', 'created_at' => $now],
                [ 'id' => '581', 'ma_quanhuyen' => '18005', 'ten_quanhuyen' => 'Huyện Tam Đảo', 'created_at' => $now],
                [ 'id' => '582', 'ma_quanhuyen' => '18006', 'ten_quanhuyen' => 'Huyện Vĩnh Tường', 'created_at' => $now],
                [ 'id' => '583', 'ma_quanhuyen' => '18007', 'ten_quanhuyen' => 'Huyện Yên Lạc', 'created_at' => $now],
                [ 'id' => '584', 'ma_quanhuyen' => '18008', 'ten_quanhuyen' => 'Thành phố Vĩnh Yên', 'created_at' => $now],
                [ 'id' => '585', 'ma_quanhuyen' => '18009', 'ten_quanhuyen' => 'Thị xã Phúc Yên', 'created_at' => $now],
                [ 'id' => '586', 'ma_quanhuyen' => '19001', 'ten_quanhuyen' => 'Huyện Gia Bình', 'created_at' => $now],
                [ 'id' => '587', 'ma_quanhuyen' => '19002', 'ten_quanhuyen' => 'Huyện Lương Tài', 'created_at' => $now],
                [ 'id' => '588', 'ma_quanhuyen' => '19003', 'ten_quanhuyen' => 'Huyện Quế Võ', 'created_at' => $now],
                [ 'id' => '589', 'ma_quanhuyen' => '19004', 'ten_quanhuyen' => 'Huyện Tiên Du', 'created_at' => $now],
                [ 'id' => '590', 'ma_quanhuyen' => '19005', 'ten_quanhuyen' => 'Huyện Thuận Thành', 'created_at' => $now],
                [ 'id' => '591', 'ma_quanhuyen' => '19006', 'ten_quanhuyen' => 'Huyện Yên Phong', 'created_at' => $now],
                [ 'id' => '592', 'ma_quanhuyen' => '19007', 'ten_quanhuyen' => 'Thị xã Bắc Ninh', 'created_at' => $now],
                [ 'id' => '593', 'ma_quanhuyen' => '19008', 'ten_quanhuyen' => 'Thị xã Từ Sơn', 'created_at' => $now],
                [ 'id' => '594', 'ma_quanhuyen' => '2001', 'ten_quanhuyen' => 'Huyện Ba Vì', 'created_at' => $now],
                [ 'id' => '595', 'ma_quanhuyen' => '2002', 'ten_quanhuyen' => 'Huyện Chương Mỹ', 'created_at' => $now],
                [ 'id' => '596', 'ma_quanhuyen' => '2003', 'ten_quanhuyen' => 'Huyện Đan Phượng', 'created_at' => $now],
                [ 'id' => '597', 'ma_quanhuyen' => '2004', 'ten_quanhuyen' => 'Huyện Đông Anh', 'created_at' => $now],
                [ 'id' => '598', 'ma_quanhuyen' => '2005', 'ten_quanhuyen' => 'Huyện Gia Lâm', 'created_at' => $now],
                [ 'id' => '599', 'ma_quanhuyen' => '2006', 'ten_quanhuyen' => 'Huyện Hoài Đức', 'created_at' => $now],
                [ 'id' => '600', 'ma_quanhuyen' => '2007', 'ten_quanhuyen' => 'Huyện Mê Linh', 'created_at' => $now],
                [ 'id' => '601', 'ma_quanhuyen' => '2008', 'ten_quanhuyen' => 'Huyện Mỹ Đức', 'created_at' => $now],
                [ 'id' => '602', 'ma_quanhuyen' => '2009', 'ten_quanhuyen' => 'Huyện Phú Xuyên', 'created_at' => $now],
                [ 'id' => '603', 'ma_quanhuyen' => '2010', 'ten_quanhuyen' => 'Huyện Phúc Thọ', 'created_at' => $now],
                [ 'id' => '604', 'ma_quanhuyen' => '2011', 'ten_quanhuyen' => 'Huyện Quốc Oai', 'created_at' => $now],
                [ 'id' => '605', 'ma_quanhuyen' => '2012', 'ten_quanhuyen' => 'Huyện Sóc Sơn', 'created_at' => $now],
                [ 'id' => '606', 'ma_quanhuyen' => '2013', 'ten_quanhuyen' => 'Huyện Từ Liêm', 'created_at' => $now],
                [ 'id' => '607', 'ma_quanhuyen' => '2014', 'ten_quanhuyen' => 'Huyện Thạch Thất', 'created_at' => $now],
                [ 'id' => '608', 'ma_quanhuyen' => '2015', 'ten_quanhuyen' => 'Huyện Thanh Oai', 'created_at' => $now],
                [ 'id' => '609', 'ma_quanhuyen' => '2016', 'ten_quanhuyen' => 'Huyện Thanh Trì', 'created_at' => $now],
                [ 'id' => '610', 'ma_quanhuyen' => '2017', 'ten_quanhuyen' => 'Huyện Thường Tín', 'created_at' => $now],
                [ 'id' => '611', 'ma_quanhuyen' => '2018', 'ten_quanhuyen' => 'Huyện Ứng Hòa', 'created_at' => $now],
                [ 'id' => '612', 'ma_quanhuyen' => '2019', 'ten_quanhuyen' => 'Quận Ba Đình', 'created_at' => $now],
                [ 'id' => '613', 'ma_quanhuyen' => '2020', 'ten_quanhuyen' => 'Quận Cầu Giấy', 'created_at' => $now],
                [ 'id' => '614', 'ma_quanhuyen' => '2021', 'ten_quanhuyen' => 'Quận Đống Đa', 'created_at' => $now],
                [ 'id' => '615', 'ma_quanhuyen' => '2022', 'ten_quanhuyen' => 'Quận Hà Đông', 'created_at' => $now],
                [ 'id' => '616', 'ma_quanhuyen' => '2023', 'ten_quanhuyen' => 'Quận Hai Bà Trưng', 'created_at' => $now],
                [ 'id' => '617', 'ma_quanhuyen' => '2024', 'ten_quanhuyen' => 'Quận Hoàn Kiếm', 'created_at' => $now],
                [ 'id' => '618', 'ma_quanhuyen' => '2025', 'ten_quanhuyen' => 'Quận Hoàng Mai', 'created_at' => $now],
                [ 'id' => '619', 'ma_quanhuyen' => '2026', 'ten_quanhuyen' => 'Quận Long Biên', 'created_at' => $now],
                [ 'id' => '620', 'ma_quanhuyen' => '2027', 'ten_quanhuyen' => 'Quận Tây Hồ', 'created_at' => $now],
                [ 'id' => '621', 'ma_quanhuyen' => '2028', 'ten_quanhuyen' => 'Quận Thanh Xuân', 'created_at' => $now],
                [ 'id' => '622', 'ma_quanhuyen' => '2029', 'ten_quanhuyen' => 'Thị xã Sơn Tây', 'created_at' => $now],
                [ 'id' => '623', 'ma_quanhuyen' => '3001', 'ten_quanhuyen' => 'Huyện Bắc Mê', 'created_at' => $now],
                [ 'id' => '624', 'ma_quanhuyen' => '3002', 'ten_quanhuyen' => 'Huyện Bắc Quang', 'created_at' => $now],
                [ 'id' => '625', 'ma_quanhuyen' => '3003', 'ten_quanhuyen' => 'Huyện Đồng Văn', 'created_at' => $now],
                [ 'id' => '626', 'ma_quanhuyen' => '3004', 'ten_quanhuyen' => 'Huyện Hoàng Su Phì', 'created_at' => $now],
                [ 'id' => '627', 'ma_quanhuyen' => '3005', 'ten_quanhuyen' => 'Huyện Mèo Vạc', 'created_at' => $now],
                [ 'id' => '628', 'ma_quanhuyen' => '3006', 'ten_quanhuyen' => 'Huyện Quản Bạ', 'created_at' => $now],
                [ 'id' => '629', 'ma_quanhuyen' => '3007', 'ten_quanhuyen' => 'Huyện Quang Bình', 'created_at' => $now],
                [ 'id' => '630', 'ma_quanhuyen' => '3008', 'ten_quanhuyen' => 'Huyện Vị Xuyên', 'created_at' => $now],
                [ 'id' => '631', 'ma_quanhuyen' => '3009', 'ten_quanhuyen' => 'Huyện Xín Mần', 'created_at' => $now],
                [ 'id' => '632', 'ma_quanhuyen' => '3010', 'ten_quanhuyen' => 'Huyện Yên Minh', 'created_at' => $now],
                [ 'id' => '633', 'ma_quanhuyen' => '3011', 'ten_quanhuyen' => 'Thị xã Hà Giang', 'created_at' => $now],
                [ 'id' => '634', 'ma_quanhuyen' => '4001', 'ten_quanhuyen' => 'Huyện Bảo Lạc', 'created_at' => $now],
                [ 'id' => '635', 'ma_quanhuyen' => '4002', 'ten_quanhuyen' => 'Huyện Bảo Lâm', 'created_at' => $now],
                [ 'id' => '636', 'ma_quanhuyen' => '4003', 'ten_quanhuyen' => 'Huyện Hạ Lang', 'created_at' => $now],
                [ 'id' => '637', 'ma_quanhuyen' => '4004', 'ten_quanhuyen' => 'Huyện Hà Quảng', 'created_at' => $now],
                [ 'id' => '638', 'ma_quanhuyen' => '4005', 'ten_quanhuyen' => 'Huyện Hoà An', 'created_at' => $now],
                [ 'id' => '639', 'ma_quanhuyen' => '4006', 'ten_quanhuyen' => 'Huyện Nguyên Bình', 'created_at' => $now],
                [ 'id' => '640', 'ma_quanhuyen' => '4007', 'ten_quanhuyen' => 'Huyện Phục Hoà', 'created_at' => $now],
                [ 'id' => '641', 'ma_quanhuyen' => '4008', 'ten_quanhuyen' => 'Huyện Quảng Uyên', 'created_at' => $now],
                [ 'id' => '642', 'ma_quanhuyen' => '4009', 'ten_quanhuyen' => 'Huyện Thạch An', 'created_at' => $now],
                [ 'id' => '643', 'ma_quanhuyen' => '4010', 'ten_quanhuyen' => 'Huyện Thông Nông', 'created_at' => $now],
                [ 'id' => '644', 'ma_quanhuyen' => '4011', 'ten_quanhuyen' => 'Huyện Trà Lĩnh', 'created_at' => $now],
                [ 'id' => '645', 'ma_quanhuyen' => '4012', 'ten_quanhuyen' => 'Huyện Trùng Khánh', 'created_at' => $now],
                [ 'id' => '646', 'ma_quanhuyen' => '4013', 'ten_quanhuyen' => 'Thị xã Cao Bằng', 'created_at' => $now],
                [ 'id' => '647', 'ma_quanhuyen' => '5001', 'ten_quanhuyen' => 'Huyện Ba Bể', 'created_at' => $now],
                [ 'id' => '648', 'ma_quanhuyen' => '5002', 'ten_quanhuyen' => 'Huyện Bạch Thông', 'created_at' => $now],
                [ 'id' => '649', 'ma_quanhuyen' => '5003', 'ten_quanhuyen' => 'Huyện Chợ Đồn', 'created_at' => $now],
                [ 'id' => '650', 'ma_quanhuyen' => '5004', 'ten_quanhuyen' => 'Huyện Chợ Mới', 'created_at' => $now],
                [ 'id' => '651', 'ma_quanhuyen' => '5005', 'ten_quanhuyen' => 'Huyện Na Rì', 'created_at' => $now],
                [ 'id' => '652', 'ma_quanhuyen' => '5006', 'ten_quanhuyen' => 'Huyện Ngân Sơn', 'created_at' => $now],
                [ 'id' => '653', 'ma_quanhuyen' => '5007', 'ten_quanhuyen' => 'Huyện Pác Nặm', 'created_at' => $now],
                [ 'id' => '654', 'ma_quanhuyen' => '5008', 'ten_quanhuyen' => 'Thị xã Bắc Kạn', 'created_at' => $now],
                [ 'id' => '655', 'ma_quanhuyen' => '6001', 'ten_quanhuyen' => 'Huyện Chiêm Hóa', 'created_at' => $now],
                [ 'id' => '656', 'ma_quanhuyen' => '6002', 'ten_quanhuyen' => 'Huyện Hàm Yên', 'created_at' => $now],
                [ 'id' => '657', 'ma_quanhuyen' => '6003', 'ten_quanhuyen' => 'Huyện Lâm Bình', 'created_at' => $now],
                [ 'id' => '658', 'ma_quanhuyen' => '6004', 'ten_quanhuyen' => 'Huyện Nà Hang', 'created_at' => $now],
                [ 'id' => '659', 'ma_quanhuyen' => '6005', 'ten_quanhuyen' => 'Huyện Sơn Dương', 'created_at' => $now],
                [ 'id' => '660', 'ma_quanhuyen' => '6006', 'ten_quanhuyen' => 'Huyện Yên Sơn', 'created_at' => $now],
                [ 'id' => '661', 'ma_quanhuyen' => '6007', 'ten_quanhuyen' => 'Thành phố Tuyên Quang', 'created_at' => $now],
                [ 'id' => '662', 'ma_quanhuyen' => '7001', 'ten_quanhuyen' => 'Huyện Bảo Thắng', 'created_at' => $now],
                [ 'id' => '663', 'ma_quanhuyen' => '7002', 'ten_quanhuyen' => 'Huyện Bảo Yên', 'created_at' => $now],
                [ 'id' => '664', 'ma_quanhuyen' => '7003', 'ten_quanhuyen' => 'Huyện Bát Xát', 'created_at' => $now],
                [ 'id' => '665', 'ma_quanhuyen' => '7004', 'ten_quanhuyen' => 'Huyện Bắc Hà', 'created_at' => $now],
                [ 'id' => '666', 'ma_quanhuyen' => '7005', 'ten_quanhuyen' => 'Huyện Mường Khương', 'created_at' => $now],
                [ 'id' => '667', 'ma_quanhuyen' => '7006', 'ten_quanhuyen' => 'Huyện Sa Pa', 'created_at' => $now],
                [ 'id' => '668', 'ma_quanhuyen' => '7007', 'ten_quanhuyen' => 'Huyện Si Ma Cai', 'created_at' => $now],
                [ 'id' => '669', 'ma_quanhuyen' => '7008', 'ten_quanhuyen' => 'Huyện Văn Bàn', 'created_at' => $now],
                [ 'id' => '670', 'ma_quanhuyen' => '7009', 'ten_quanhuyen' => 'Thị xã Lào Cai', 'created_at' => $now],
                [ 'id' => '671', 'ma_quanhuyen' => '8001', 'ten_quanhuyen' => 'Huyện Điện Biên', 'created_at' => $now],
                [ 'id' => '672', 'ma_quanhuyen' => '8002', 'ten_quanhuyen' => 'Huyện Điện Biên Đông', 'created_at' => $now],
                [ 'id' => '673', 'ma_quanhuyen' => '8003', 'ten_quanhuyen' => 'Huyện Mường Ảng', 'created_at' => $now],
                [ 'id' => '674', 'ma_quanhuyen' => '8004', 'ten_quanhuyen' => 'Huyện Mường Chà', 'created_at' => $now],
                [ 'id' => '675', 'ma_quanhuyen' => '8005', 'ten_quanhuyen' => 'Huyện Mường Nhé', 'created_at' => $now],
                [ 'id' => '676', 'ma_quanhuyen' => '8006', 'ten_quanhuyen' => 'Huyện Tủa Chùa', 'created_at' => $now],
                [ 'id' => '677', 'ma_quanhuyen' => '8007', 'ten_quanhuyen' => 'Huyện Tuần Giáo', 'created_at' => $now],
                [ 'id' => '678', 'ma_quanhuyen' => '8008', 'ten_quanhuyen' => 'Thành phố Điện Biên Phủ', 'created_at' => $now],
                [ 'id' => '679', 'ma_quanhuyen' => '8009', 'ten_quanhuyen' => 'Thị xã Mường Lay', 'created_at' => $now],
                [ 'id' => '680', 'ma_quanhuyen' => '9001', 'ten_quanhuyen' => 'Huyện Mường Tè', 'created_at' => $now],
                [ 'id' => '681', 'ma_quanhuyen' => '9002', 'ten_quanhuyen' => 'Huyện Phong Thổ', 'created_at' => $now],
                [ 'id' => '682', 'ma_quanhuyen' => '9003', 'ten_quanhuyen' => 'Huyện Sìn Hồ', 'created_at' => $now],
                [ 'id' => '683', 'ma_quanhuyen' => '9004', 'ten_quanhuyen' => 'Huyện Tam Đường', 'created_at' => $now],
                [ 'id' => '684', 'ma_quanhuyen' => '9005', 'ten_quanhuyen' => 'Huyện Tân Uyên', 'created_at' => $now],
                [ 'id' => '685', 'ma_quanhuyen' => '9006', 'ten_quanhuyen' => 'Huyện Than Uyên', 'created_at' => $now],
                [ 'id' => '686', 'ma_quanhuyen' => '38001', 'ten_quanhuyen' => 'Huyện Bác Ái', 'created_at' => $now],
                [ 'id' => '687', 'ma_quanhuyen' => '38002', 'ten_quanhuyen' => 'Huyện Ninh Hải', 'created_at' => $now],
                [ 'id' => '688', 'ma_quanhuyen' => '38003', 'ten_quanhuyen' => 'Huyện Ninh Phước', 'created_at' => $now],
                [ 'id' => '689', 'ma_quanhuyen' => '38004', 'ten_quanhuyen' => 'Huyện Ninh Sơn', 'created_at' => $now],
                [ 'id' => '690', 'ma_quanhuyen' => '38005', 'ten_quanhuyen' => 'Huyện Thuận Bắc', 'created_at' => $now],
                [ 'id' => '691', 'ma_quanhuyen' => '38006', 'ten_quanhuyen' => 'Huyện Thuận Nam', 'created_at' => $now],
                [ 'id' => '692', 'ma_quanhuyen' => '38007', 'ten_quanhuyen' => 'Thành phố Phan Rang-Tháp Chàm', 'created_at' => $now],
                [ 'id' => '693', 'ma_quanhuyen' => '', 'ten_quanhuyen' => 'Huyện Tân Uyên', 'created_at' => $now],
                [ 'id' => '694', 'ma_quanhuyen' => '56008', 'ten_quanhuyen' => 'Huyện Bình Tân', 'created_at' => $now],
                [ 'id' => '695', 'ma_quanhuyen' => '60005.', 'ten_quanhuyen' => 'TTYT Quận Bình Thủy', 'created_at' => $now],
                [ 'id' => '696', 'ma_quanhuyen' => '60009.', 'ten_quanhuyen' => 'TTYTDP Thốt Nốt', 'created_at' => $now],
            ]
        );

        DB::statement('ALTER TABLE `hrm_quanhuyen` AUTO_INCREMENT=1;');
    }
}
